function fun = invertedPendulumAndCartOptimalControl(in1,in2)
%invertedPendulumAndCartOptimalControl
%    FUN = invertedPendulumAndCartOptimalControl(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Jan-2024 16:16:30

l = in2(2,:);
lambda_3 = in1(7,:);
lambda_4 = in1(8,:);
m_c = in2(3,:);
m_p = in2(4,:);
theta = in1(2,:);
t2 = cos(theta);
fun = -(l.*lambda_3-lambda_4.*t2)./(l.*m_c.*2.0+l.*m_p.*2.0-l.*m_p.*t2.^2.*2.0);
