function out1 = invertedPendulumAndCartOptimalControl(in1,in2)
%invertedPendulumAndCartOptimalControl
%    OUT1 = invertedPendulumAndCartOptimalControl(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Jan-2024 22:08:55

I_yy = in2(1,:);
l = in2(4,:);
lambda_3 = in1(7,:);
lambda_4 = in1(8,:);
m_c = in2(5,:);
m_p = in2(6,:);
theta = in1(2,:);
t2 = cos(theta);
t3 = l.^2;
t4 = m_p.^2;
out1 = -(I_yy.*lambda_3+lambda_3.*m_p.*t3-l.*lambda_4.*m_p.*t2)./(I_yy.*m_c.*2.0+I_yy.*m_p.*2.0+t3.*t4.*2.0-t2.^2.*t3.*t4.*2.0+m_c.*m_p.*t3.*2.0);
