function out1 = invertedPendulumAndCart(in1,F_x,in3)
%invertedPendulumAndCart
%    OUT1 = invertedPendulumAndCart(IN1,F_x,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Jan-2024 21:52:14

%    states = [x theta v omega]
%    inputs = [F_x]
%    params = [I_yy b g l m_c m_p]
%
I_yy = in3(1,:);
b = in3(2,:);
g = in3(3,:);
l = in3(4,:);
m_c = in3(5,:);
m_p = in3(6,:);
omega = in1(4,:);
theta = in1(2,:);
v = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = b.*v;
t5 = m_c+m_p;
t6 = l.^2;
t7 = m_p.^2;
t8 = omega.^2;
t9 = t2.^2;
t10 = -t4;
t11 = m_p.*t6;
t13 = l.*m_p.*t3.*t8;
t12 = I_yy+t11;
t14 = t6.*t7.*t9;
t17 = F_x+t10+t13;
t15 = t5.*t12;
t16 = -t14;
t18 = t15+t16;
t19 = -1.0./(t14-t15);
out1 = [v;omega;t12.*t17.*t19+(g.*t2.*t3.*t6.*t7)./(t14-t15);(l.*m_p.*t2.*t17)./(t14-t15)+g.*l.*m_p.*t3.*t5.*t19];
