function fun = invertedPendulumAndCartPMP(in1,in2)
%invertedPendulumAndCartPMP
%    FUN = invertedPendulumAndCartPMP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Jan-2024 16:16:33

g = in2(1,:);
l = in2(2,:);
lambda_1 = in1(5,:);
lambda_2 = in1(6,:);
lambda_3 = in1(7,:);
lambda_4 = in1(8,:);
m_c = in2(3,:);
m_p = in2(4,:);
omega = in1(4,:);
r = in1(9,:);
theta = in1(2,:);
v = in1(3,:);
x = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = l.^2;
t5 = l.^3;
t6 = lambda_4.^2;
t7 = m_c.*2.0;
t8 = m_c.^2;
t9 = m_c.^3;
t10 = m_p.^2;
t11 = m_p.^3;
t12 = omega.^2;
t13 = theta.*2.0;
t14 = theta.*3.0;
t15 = theta.*4.0;
t16 = theta.*5.0;
t17 = cos(t13);
t18 = cos(t14);
t19 = cos(t15);
t20 = cos(t16);
t21 = sin(t13);
t22 = sin(t14);
t23 = sin(t15);
t24 = 1.0./t4;
t25 = m_p.*t17;
t26 = -t25;
t27 = m_p+t7+t26;
t28 = 1.0./t27.^2;
et1 = m_c.*t6.*t21.*4.0+m_p.*t6.*t21.*6.0+m_p.*t6.*t23+t4.*t9.*theta.*3.2e+1+t4.*t11.*theta.*1.0e+1-g.*lambda_3.*t4.*t11.*6.0+lambda_4.*t4.*t11.*t12.*6.0+m_c.*t4.*t10.*theta.*3.6e+1+m_p.*t4.*t8.*theta.*4.8e+1-t4.*t11.*t17.*theta.*1.5e+1+t4.*t11.*t19.*theta.*6.0-t4.*t8.*t25.*theta.*4.8e+1+lambda_3.^2.*m_p.*t4.*t21.*8.0-t4.*t11.*theta.*cos(theta.*6.0)-l.*lambda_3.*lambda_4.*m_c.*t3.*8.0-l.*lambda_3.*lambda_4.*m_p.*t3.*1.4e+1-l.*lambda_3.*lambda_4.*m_p.*t22.*6.0-g.*l.*lambda_4.*t2.*t9.*1.6e+1+g.*l.*lambda_4.*t2.*t11.*2.0-g.*l.*lambda_4.*t11.*t18.*3.0+g.*l.*lambda_4.*t11.*t20-g.*lambda_3.*m_c.*t4.*t10.*1.2e+1+g.*lambda_3.*t4.*t11.*t17.*8.0-g.*lambda_3.*t4.*t11.*t19.*2.0+g.*lambda_3.*t4.*t8.*t25.*1.6e+1+lambda_4.*m_c.*t4.*t10.*t12.*1.2e+1-lambda_3.*t2.*t5.*t11.*t12.*2.0;
et2 = lambda_4.*t4.*t11.*t12.*t17.*-8.0+lambda_3.*t5.*t11.*t12.*t18.*3.0+lambda_4.*t4.*t11.*t12.*t19.*2.0-lambda_3.*t5.*t11.*t12.*t20-lambda_4.*t4.*t8.*t12.*t25.*1.6e+1-m_c.*t4.*t10.*t17.*theta.*4.8e+1+m_c.*t4.*t10.*t19.*theta.*1.2e+1-lambda_4.*m_c.*t4.*t10.*t12.*t17.*1.6e+1+lambda_4.*m_c.*t4.*t10.*t12.*t19.*4.0+lambda_3.*m_p.*t2.*t5.*t8.*t12.*1.6e+1-g.*l.*lambda_4.*m_c.*t10.*t18.*3.0+g.*l.*lambda_4.*m_c.*t10.*t20-g.*l.*lambda_4.*m_p.*t2.*t8.*1.6e+1+g.*l.*lambda_4.*t2.*t7.*t10+g.*lambda_3.*m_c.*t4.*t10.*t17.*1.6e+1-g.*lambda_3.*m_c.*t4.*t10.*t19.*4.0;
mt1 = [r.*v;omega.*r;(r.*t28.*(-l.*lambda_3+lambda_4.*t2+(g.*l.*t10.*t21)./2.0-(g.*l.*t10.*t23)./4.0+t3.*t4.*t10.*t12.*(3.0./2.0)-(t4.*t10.*t12.*t22)./2.0+g.*l.*m_c.*m_p.*t21+m_p.*t3.*t4.*t7.*t12).*2.0)./l;r.*t24.*t28.*(lambda_4./2.0+(lambda_4.*t17)./2.0-l.*lambda_3.*t2+g.*l.*t3.*t10.*(3.0./2.0)-(g.*l.*t10.*t22)./2.0+(t4.*t10.*t12.*t21)./2.0-(t4.*t10.*t12.*t23)./4.0+g.*l.*m_c.*m_p.*t3.*(7.0./2.0)-(g.*l.*m_c.*m_p.*t22)./2.0+g.*l.*m_c.*t3.*t7+m_c.*m_p.*t4.*t12.*t21).*-2.0;r.*x.*-2.0;r.*t24.*1.0./t27.^3.*(et1+et2).*(-1.0./2.0);-r.*(lambda_1+v.*2.0)];
mt2 = [-lambda_2.*r-omega.*r.*2.0+(lambda_4.*m_p.*omega.*r.*t2.*t3.*4.0)./(m_p.*2.0+t7-m_p.*t2.^2.*2.0)-(l.*lambda_3.*m_p.*omega.*r.*t3.*2.0)./(m_c+m_p.*t3.^2);0.0];
fun = [mt1;mt2];
