function out1 = rollingDisk(in1,in2,in3)
%rollingDisk
%    OUT1 = rollingDisk(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Feb-2024 01:41:10

%    states = [x y psi varphi theta u_1 u_2 u_3]
%    inputs = []
%    params = [g m r]
%
g = in3(1,:);
m = in3(2,:);
psi = in1(3,:);
r = in3(3,:);
u_1 = in1(6,:);
u_2 = in1(7,:);
u_3 = in1(8,:);
varphi = in1(4,:);
t2 = cos(varphi);
t3 = sin(varphi);
t4 = m.^2;
t5 = r.^2;
t7 = varphi.*2.0;
t6 = t5.^2;
t8 = sin(t7);
t9 = t3.^2;
t10 = t2.*u_3.*2.0;
t12 = (m.*t5)./4.0;
t11 = t8.*u_1.*5.0;
t13 = m.*t5.*t9.*(5.0./4.0);
t15 = t4.*t6.*t9.*(9.0./4.0);
t14 = t10+t11;
t16 = t12+t13;
t17 = m.*t5.*t16.*(3.0./2.0);
t18 = -t17;
t19 = t15+t18;
t20 = 1.0./t19;
out1 = [r.*u_3.*cos(psi);r.*u_3.*sin(psi);u_1;u_2;u_3;t4.*t6.*t14.*t20.*u_2.*(3.0./8.0)-t2.*t3.*t4.*t6.*t20.*u_1.*u_2.*(1.5e+1./4.0);((g.*m.*r.*t3+m.*t2.*t5.*u_1.*u_3.*(3.0./2.0)+m.*t2.*t3.*t5.*u_1.^2.*(5.0./4.0)).*(4.0./5.0))./(m.*t5);t3.*t4.*t6.*t14.*t20.*u_2.*(-3.0./8.0)+m.*t2.*t5.*t16.*t20.*u_1.*u_2.*(5.0./2.0)];
