function f = rrarmForcingVector(in1,in2,in3)
%rrarmForcingVector
%    F = rrarmForcingVector(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    20-Jun-2026 21:23:28

%   states = [theta_1 theta_2 omega_1 omega_2]
%   inputs = [tau_1 tau_2]
%   params = [I_yy1 I_yy2 m_1 m_2 l_1 l_2 b_1 b_2 g]
%
b_1 = in3(7,:);
b_2 = in3(8,:);
g = in3(9,:);
l_1 = in3(5,:);
l_2 = in3(6,:);
m_1 = in3(3,:);
m_2 = in3(4,:);
omega_1 = in1(3,:);
omega_2 = in1(4,:);
tau_1 = in2(1,:);
tau_2 = in2(2,:);
theta_1 = in1(1,:);
theta_2 = in1(2,:);
t2 = cos(theta_1);
t3 = sin(theta_2);
t4 = theta_1+theta_2;
t5 = cos(t4);
t6 = (g.*l_2.*m_2.*t5)./2.0;
f = [omega_1;omega_2;t6+tau_1-b_1.*omega_1+(g.*l_1.*m_1.*t2)./2.0+g.*l_1.*m_2.*t2+(l_1.*l_2.*m_2.*omega_2.^2.*t3)./2.0+l_1.*l_2.*m_2.*omega_1.*omega_2.*t3;t6+tau_2-b_2.*omega_2-(l_1.*l_2.*m_2.*omega_1.^2.*t3)./2.0];
end
