function M = rrarmMassMatrix(in1,in2,in3)
%rrarmMassMatrix
%    M = rrarmMassMatrix(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    20-Jun-2026 21:23:27

%   states = [theta_1 theta_2 omega_1 omega_2]
%   inputs = [tau_1 tau_2]
%   params = [I_yy1 I_yy2 m_1 m_2 l_1 l_2 b_1 b_2 g]
%
I_yy1 = in3(1,:);
I_yy2 = in3(2,:);
l_1 = in3(5,:);
l_2 = in3(6,:);
m_1 = in3(3,:);
m_2 = in3(4,:);
theta_2 = in1(2,:);
t2 = cos(theta_2);
t3 = l_1.^2;
t4 = l_2.^2;
t5 = (m_2.*t4)./4.0;
t6 = (l_1.*l_2.*m_2.*t2)./2.0;
t7 = I_yy2+t5+t6;
M = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,I_yy1+I_yy2+t5+(m_1.*t3)./4.0+m_2.*t3+l_1.*l_2.*m_2.*t2,t7,0.0,0.0,t7,I_yy2+t5],[4,4]);
end
