function J = prydeMotorcycleKinematicJacobian(in1,in2)
%prydeMotorcycleKinematicJacobian
%    J = prydeMotorcycleKinematicJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Jul-2025 14:28:45

%   states = [psi p_x p_y varphi theta_r delta theta_f theta psi_f p_fx p_fy varphi_f]
%   inputs = [omega_bz v_rx v_ry omega_bx omega_r omega_delta omega_f omega_by omega_fz v_fx v_fy omega_fx]
%   params = [A C_d C_delta C_l C_p I_bxx I_bxz I_byy I_bzz I_hxx I_hzz K_ycf K_ycr K_yvf K_yvr a a_n b e f f_zf0 f_zr0 g h i_fy i_ry m_b m_f m_h m_r p_Kxf1 p_Kxf2 p_Kxf3 p_Kxr1 p_Kxr2 p_Kxr3 p_Kyf1 p_Kyf2 p_Kyf3 p_Kyf6 p_Kyf7 p_Kyr1 p_Kyr2 p_Kyr3 p_Kyr6 p_Kyr7 q_dzf1 q_dzf2 q_dzf8 q_dzf9 q_dzr1 q_dzr2 q_dzr8 q_dzr9 rho rho_f rho_r t_f t_r varepsilon]
%
psi_f = in1(9,:);
psi = in1(1,:);
rho_f = in2(56,:);
rho_r = in2(57,:);
theta = in1(8,:);
varphi = in1(4,:);
varphi_f = in1(12,:);
t2 = cos(psi_f);
t3 = cos(psi);
t4 = cos(theta);
t5 = cos(varphi);
t6 = cos(varphi_f);
t7 = sin(psi_f);
t8 = sin(psi);
t9 = sin(theta);
t10 = sin(varphi);
t11 = t5.^2;
t12 = t6.^2;
t13 = 1.0./t5;
t14 = 1.0./t6;
t15 = t11-1.0;
t16 = t12-1.0;
mt1 = [t4.*t13,rho_r.*t8.*t9.*t13.*t15,-rho_r.*t3.*t9.*t13.*t15,t9,0.0,0.0,0.0,-t4.*t10.*t13,0.0,0.0,0.0,0.0,0.0,t3,t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t8.*t13,t3.*t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t9.*t13,rho_r.*t4.*t8.*t13.*t15,-rho_r.*t3.*t4.*t13.*t15,t4,0.0,0.0,0.0,t9.*t10.*t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t7.*t14,t2.*t14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,rho_f.*t7.*t14.*t16];
mt2 = [-rho_f.*t2.*t14.*t16,1.0];
J = reshape([mt1,mt2],12,12);
end
