function Jslip = prydeMotorcycleSlipAngleJacobian(A,C_d,C_delta,C_l,C_p,I_bxx,I_bxz,I_bzz,I_hxx,I_hzz,K_ycf,K_ycr,K_yvf,K_yvr,V,a,a_n,b,e,f,f_zf0,f_zr0,g,h,i_fy,i_ry,m_b,m_f,m_h,m_r,p_Kxf1,p_Kxf2,p_Kyf1,p_Kxf3,p_Kyf2,p_Kyf3,p_Kyf6,p_Kyf7,p_Kxr1,p_Kxr2,p_Kyr1,p_Kxr3,p_Kyr2,p_Kyr3,p_Kyr6,p_Kyr7,q_dzf1,q_dzf2,q_dzf8,q_dzf9,q_dzr1,q_dzr2,q_dzr8,q_dzr9,rho,rho_f,rho_r,t_f,t_r,varepsilon)
%prydeMotorcycleSlipAngleJacobian
%    Jslip = prydeMotorcycleSlipAngleJacobian(A,C_d,C_delta,C_l,C_p,I_bxx,I_bxz,I_bzz,I_hxx,I_hzz,K_ycf,K_ycr,K_yvf,K_yvr,V,a,A_N,B,E,F,F_ZF0,F_ZR0,G,H,I_FY,I_RY,M_B,M_F,M_H,M_R,p_Kxf1,p_Kxf2,p_Kyf1,p_Kxf3,p_Kyf2,p_Kyf3,p_Kyf6,p_Kyf7,p_Kxr1,p_Kxr2,p_Kyr1,p_Kxr3,p_Kyr2,p_Kyr3,p_Kyr6,p_Kyr7,Q_DZF1,Q_DZF2,Q_DZF8,Q_DZF9,Q_DZR1,Q_DZR2,Q_DZR8,Q_DZR9,RHO,RHO_F,RHO_R,T_F,T_R,VAREPSILON)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-Jul-2025 20:58:06

t2 = cos(varepsilon);
t3 = 1.0./V;
Jslip = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t2,0.0,(t3.*(a-a_n+b.*t2))./t2,t3,t3,rho_r.*t3,t3.*(rho_r-t_f+t_r),0.0,-t3.*(a_n-t_f.*sin(varepsilon))],[2,9]);
end
