function Jg = prydeMotoCamberJacobian(in1)
%prydeMotoCamberJacobian
%    Jg = prydeMotoCamberJacobian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Oct-2025 02:16:31

varepsilon = in1(60,:);
Jg = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,-sin(varepsilon),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,12]);
end
