function Ja = prydeMotoSlipAngleJacobian(in1)
%prydeMotoSlipAngleJacobian
%    Ja = prydeMotoSlipAngleJacobian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Oct-2025 03:45:43

V = in1(15,:);
a = in1(16,:);
a_n = in1(17,:);
b = in1(18,:);
rho_f = in1(56,:);
rho_r = in1(57,:);
t_f = in1(58,:);
t_r = in1(59,:);
varepsilon = in1(60,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = 1.0./V;
t5 = -a_n;
Ja = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t2,0.0,(t4.*(a+t5+b.*t2))./t2,t4,t4,rho_r.*t4,rho_f.*t4-t4.*(rho_f-rho_r+t_f-t_r),0.0,t4.*(t5+rho_f.*t3+t3.*t_f)-rho_f.*t3.*t4],[2,12]);
end
