function Mr = prydeMotorcycleLinearizedMassMatrix(V,in2)
%prydeMotorcycleLinearizedMassMatrix
%    Mr = prydeMotorcycleLinearizedMassMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Jun-2024 01:05:02

C_rxz = in2(6,:);
I_fx = in2(7,:);
I_fz = in2(8,:);
I_rx = in2(9,:);
I_rz = in2(10,:);
b = in2(14,:);
e = in2(15,:);
h = in2(17,:);
j = in2(20,:);
k = in2(21,:);
m_f = in2(22,:);
m_r = in2(23,:);
varepsilon = in2(27,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = b.*m_f;
t5 = b.*m_r;
t6 = e.*m_f;
t7 = h.*m_r;
t8 = j.*m_f;
t9 = k.*m_f;
t10 = b.^2;
t11 = varepsilon.*2.0;
t12 = sin(t11);
t13 = t3.^2;
t14 = I_fz.*t2;
t15 = I_fz.*t3;
t16 = e.*t4;
t17 = h.*t5;
t18 = j.*t4;
t19 = j.*t6;
t20 = k.*t6;
t21 = k.*t8;
t24 = t7+t8;
t29 = t4+t5+t9;
t22 = I_fx.*t13;
t23 = I_fz.*t13;
t25 = t15+t19;
t26 = (I_fx.*t12)./2.0;
t27 = (I_fz.*t12)./2.0;
t30 = t14+t16+t20;
t28 = -t26;
t31 = C_rxz+t17+t18+t21+t27+t28;
Mr = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,m_f+m_r,t29,t24,t6,0.0,0.0,t29,I_fz+I_rz+t22-t23+b.*t4+b.*t5+k.*t4.*2.0+k.*t9,t31,t30,0.0,0.0,t24,t31,I_fx+I_rx-t22+t23+h.*t7+j.*t8,t25,0.0,0.0,t6,t30,t25,I_fz+e.*t6],[6,6]);
