function b = slipAngleVector(in1)
%slipAngleVector
%    B = slipAngleVector(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Jul-2025 10:07:29

b = [0.0;0.0];
end
