function out1 = travelingInvertedPendulum(in1,in2,in3)
%travelingInvertedPendulum
%    OUT1 = travelingInvertedPendulum(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Jan-2024 17:45:06

%    states = [x y psi varphi u_1 u_2 u_3]
%    inputs = [F_x M_z]
%    params = [I_xx I_zz g l m]
%
F_x = in2(1,:);
I_xx = in3(1,:);
I_zz = in3(2,:);
M_z = in2(2,:);
g = in3(3,:);
l = in3(4,:);
m = in3(5,:);
psi = in1(3,:);
u_1 = in1(5,:);
u_2 = in1(6,:);
u_3 = in1(7,:);
varphi = in1(4,:);
t2 = cos(varphi);
t3 = sin(varphi);
t4 = l.^2;
t5 = m.^2;
t6 = u_2.^2;
t7 = varphi.*2.0;
t8 = sin(t7);
t9 = t3.^2;
t13 = l.*m.*t2.*u_2.*u_3.*2.0;
t10 = I_zz.*t9;
t11 = I_zz.*t8.*u_2.*u_3;
t14 = m.*t4.*t9;
t15 = -t13;
t16 = t4.*t5.*t9;
t18 = m.*t4.*t8.*u_2.*u_3;
t12 = -t10;
t17 = F_x+t15;
t19 = -t16;
t20 = -t18;
t21 = I_zz+t12+t14;
t23 = M_z+t11+t20;
t22 = m.*t21;
t24 = t19+t22;
t25 = -1.0./(t16-t22);
out1 = [u_1.*cos(psi);u_1.*sin(psi);u_2;u_3;t17.*t21.*t25+(l.*m.*t3.*t23)./(t16-t22);m.*t23.*t25+(l.*m.*t3.*t17)./(t16-t22);-((I_zz.*t6.*t8)./2.0+g.*l.*m.*t3-(m.*t4.*t6.*t8)./2.0-l.*m.*t2.*u_1.*u_2)./(I_xx+m.*t4)];
