function pmp_eqs = travelingInvertedPendulumPMP(in1,g)
%travelingInvertedPendulumPMP
%    PMP_EQS = travelingInvertedPendulumPMP(IN1,G)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Jan-2024 17:54:46

lambda_1 = in1(8,:);
lambda_2 = in1(9,:);
lambda_3 = in1(10,:);
lambda_4 = in1(11,:);
lambda_5 = in1(12,:);
lambda_6 = in1(13,:);
lambda_7 = in1(14,:);
psi = in1(3,:);
u_1 = in1(5,:);
u_2 = in1(6,:);
u_3 = in1(7,:);
varphi = in1(4,:);
t2 = cos(psi);
t3 = cos(varphi);
t4 = sin(psi);
t5 = sin(varphi);
t6 = lambda_5.^2;
t7 = u_2.^2;
t8 = varphi.*2.0;
t9 = sin(t8);
t10 = t5.^2;
t11 = t5.^3;
mt1 = [t2.*u_1;t4.*u_1;u_2;u_3;-lambda_5+lambda_6.*t5.*2.0-lambda_5.*t10.*3.0+lambda_6.*t11-lambda_5.*t10.^2-t3.*u_2.*u_3.*2.0;-lambda_6+lambda_5.*t5.*2.0+lambda_5.*t11-lambda_6.*t10;(g.*t5)./2.0+(t3.*t5.*t7)./2.0+(t3.*u_1.*u_2)./2.0;0.0;0.0;-u_1.*(lambda_2.*t2-lambda_1.*t4);t6.*sin(varphi.*4.0).*(-1.0./4.0)+t6.*t9.*2.0+(lambda_6.^2.*t9)./2.0-(lambda_7.*t7.*cos(t8))./2.0+lambda_5.*lambda_6.*cos(varphi.*3.0).*(3.0./4.0)-(g.*lambda_7.*t3)./2.0-lambda_5.*lambda_6.*t3.*(1.1e+1./4.0)-lambda_5.*t5.*u_2.*u_3.*2.0+(lambda_7.*t5.*u_1.*u_2)./2.0;-lambda_1.*t2-lambda_2.*t4-(lambda_7.*t3.*u_2)./2.0];
mt2 = [-lambda_3+lambda_5.*t3.*u_3.*2.0-(lambda_7.*t3.*u_1)./2.0-(lambda_7.*t9.*u_2)./2.0;-lambda_4+lambda_5.*t3.*u_2.*2.0];
pmp_eqs = [mt1;mt2];
