function front_tire_eqns = frontTireEqns(in1)
%frontTireEqns
%    FRONT_TIRE_EQNS = frontTireEqns(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    02-Oct-2025 05:51:34

A = in1(1,:);
C_l = in1(4,:);
C_p = in1(5,:);
V = in1(15,:);
a = in1(16,:);
a_n = in1(17,:);
b = in1(18,:);
e = in1(19,:);
f = in1(20,:);
f_zf0 = in1(21,:);
g = in1(23,:);
m_b = in1(27,:);
m_f = in1(28,:);
m_h = in1(29,:);
p_Kxf1 = in1(31,:);
p_Kxf2 = in1(32,:);
p_Kyf1 = in1(33,:);
p_Kxf3 = in1(34,:);
p_Kyf2 = in1(35,:);
p_Kyf3 = in1(36,:);
p_Kyf6 = in1(37,:);
p_Kyf7 = in1(38,:);
q_dzf1 = in1(47,:);
q_dzf2 = in1(48,:);
q_dzf8 = in1(49,:);
q_dzf9 = in1(50,:);
rho = in1(55,:);
t_f = in1(58,:);
varepsilon = in1(60,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = g.*m_f;
t5 = V.^2;
t10 = -a_n;
t11 = 1.0./f_zf0;
t12 = 1.0./p_Kyf3;
t6 = a.*t2;
t7 = b.*t2;
t8 = e.*t2;
t9 = f.*t3;
t13 = -t4;
t15 = (A.*C_l.*rho.*t5)./4.0;
t16 = (A.*C_p.*rho.*t5)./2.0;
t14 = -t9;
t17 = a+t7+t10;
t18 = -t15;
t19 = -t16;
t20 = 1.0./t17;
t21 = b+t6+t8+t14;
t22 = g.*m_b.*t7.*t20;
t24 = g.*m_h.*t2.*t20.*t21;
t23 = -t22;
t25 = -t24;
t26 = t4+t18+t19+t22+t24;
t27 = f_zf0+t13+t15+t16+t23+t25;
t28 = t11.*t12.*t26;
t29 = atan(t28);
t30 = p_Kyf2.*t29;
t31 = sin(t30);
front_tire_eqns = [t26;t26.*exp(-p_Kxf3.*t11.*t27).*(p_Kxf1-p_Kxf2.*t11.*t27);f_zf0.*p_Kyf1.*t31;t26.*(p_Kyf6-p_Kyf7.*t11.*t27);-p_Kyf1.*t26.*t31.*t_f.*(q_dzf1-q_dzf2.*t11.*t27);t26.*t_f.*(q_dzf8-q_dzf9.*t11.*t27)];
end
