function out1 = pendulum2d(in1,in2)
%PENDULUM2D
%    OUT1 = PENDULUM2D(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    07-Jun-2026 01:45:21

g = in2(2,:);
l = in2(1,:);
omega_phi = in1(4,:);
omega_theta = in1(3,:);
phi = in1(2,:);
theta = in1(1,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = 1.0./l;
out1 = [omega_theta;omega_phi;(t4.*(g.*sin(theta).*3.0-l.*omega_phi.*omega_theta.*t3.*4.0).*(-1.0./2.0))./t2;t3.*t4.*(g.*cos(theta).*3.0+l.*omega_theta.^2.*t2.*2.0).*(-1.0./2.0)];
end
