function out1 = pendulum2d(in1,in2)
%PENDULUM2D
%    OUT1 = PENDULUM2D(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    04-Jun-2026 00:21:01

g = in2(2,:);
l = in2(1,:);
phi = in1(2,:);
theta = in1(1,:);
v_x = in1(3,:);
v_y = in1(4,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = 1.0./l;
t5 = 1.0./t2;
out1 = [t4.*t5.*v_x.*-2.0;t4.*v_y.*2.0;g.*sin(theta).*(3.0./4.0)+t3.*t4.*t5.*v_x.*v_y.*2.0;t3.*t4.*t5.*(v_x.^2.*8.0+g.*l.*t2.*cos(theta).*3.0).*(-1.0./4.0)];
end
