function B = dynamicBicycleInputMatrix(in1,in2)
%dynamicBicycleInputMatrix
%    B = dynamicBicycleInputMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    26-Sep-2024 00:54:54

%   states = [omega_z v_x v_y]
%   inputs = [delta a_x]
%   params = [C_f C_r I_zz V l_f l_r m]
%
C_f = in2(1,:);
I_zz = in2(3,:);
l_f = in2(5,:);
m = in2(7,:);
B = reshape([(C_f.*l_f.*2.0)./I_zz,0.0,(C_f.*2.0)./m,0.0,1.0,0.0],[3,2]);
