function A = dynamicBicycleStateMatrix(in1,in2)
%dynamicBicycleStateMatrix
%    A = dynamicBicycleStateMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    26-Sep-2024 00:54:54

%   states = [omega_z v_x v_y]
%   inputs = [delta a_x]
%   params = [C_f C_r I_zz V l_f l_r m]
%
C_f = in2(1,:);
C_r = in2(2,:);
I_zz = in2(3,:);
V = in2(4,:);
l_f = in2(5,:);
l_r = in2(6,:);
m = in2(7,:);
t2 = 1.0./I_zz;
t3 = 1.0./V;
t4 = 1.0./m;
A = reshape([t2.*t3.*(C_f.*l_f.^2+C_r.*l_r.^2).*-2.0,0.0,-t3.*t4.*(C_f.*l_f.*2.0-C_r.*l_r.*2.0+m.*1.0./t3.^2),0.0,0.0,0.0,t2.*t3.*(C_f.*l_f-C_r.*l_r).*-2.0,0.0,t3.*t4.*(C_f+C_r).*-2.0],[3,3]);
