function Mp = motorcycleKinematicsMassMatrix(in1,in2,in3)
%motorcycleKinematicsMassMatrix
%    Mp = motorcycleKinematicsMassMatrix(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Sep-2024 10:53:22

a = in3(1,:);
b = in3(2,:);
delta = in1(4,:);
e = in3(4,:);
f = in3(5,:);
h = in3(6,:);
phi = in1(3,:);
psi = in1(1,:);
theta = in1(2,:);
varepsilon = in3(3,:);
t2 = cos(delta);
t3 = cos(phi);
t4 = cos(psi);
t5 = sin(delta);
t6 = cos(theta);
t7 = cos(varepsilon);
t8 = sin(phi);
t9 = sin(psi);
t10 = sin(theta);
t11 = sin(varepsilon);
t12 = t3.^2;
t13 = t6.^2;
mt1 = [-t2.*t7.*t10+t5.*t6.*t8+t2.*t3.*t6.*t11,t2.*t6.*t8+t5.*t7.*t10-t3.*t5.*t6.*t11,t10.*t11+t3.*t6.*t7,-h.*t5.*t10+a.*t5.*t10.*t11+f.*t2.*t6.*t8+f.*t5.*t7.*t10+a.*t3.*t5.*t6.*t7-f.*t3.*t5.*t6.*t11-h.*t2.*t6.*t7.*t8,e.*t10.*t11-h.*t2.*t10+a.*t2.*t10.*t11+e.*t3.*t6.*t7+f.*t2.*t7.*t10-f.*t5.*t6.*t8+a.*t2.*t3.*t6.*t7-f.*t2.*t3.*t6.*t11+h.*t5.*t6.*t7.*t8,-a.*t6.*t8-e.*t2.*t6.*t8-e.*t5.*t7.*t10+h.*t6.*t8.*t11+e.*t3.*t5.*t6.*t11,t3.*t5-t2.*t8.*t11,t2.*t3+t5.*t8.*t11,-t7.*t8];
mt2 = [f.*t2.*t3-a.*t5.*t7.*t8-b.*t5.*t8.*t13+f.*t5.*t8.*t11+b.*t2.*t6.*t7.*t10-b.*t2.*t3.*t11.*t13-h.*t2.*t3.*t7.*t13-h.*t3.*t5.*t6.*t8.*t10-h.*t2.*t6.*t10.*t11.*t12,-e.*t7.*t8-f.*t3.*t5-a.*t2.*t7.*t8-b.*t2.*t8.*t13+f.*t2.*t8.*t11-b.*t5.*t6.*t7.*t10+b.*t3.*t5.*t11.*t13+h.*t3.*t5.*t7.*t13-h.*t2.*t3.*t6.*t8.*t10+h.*t5.*t6.*t10.*t11.*t12,-a.*t3-e.*t2.*t3-b.*t3.*t7.*t13-b.*t6.*t10.*t11-e.*t5.*t8.*t11+h.*t3.*t11.*t13-h.*t6.*t7.*t10.*t12,t2.*t7,-t5.*t7,-t11];
mt3 = [h.*t5-a.*t5.*t11-f.*t5.*t7-h.*t5.*t13+h.*t5.*t12.*t13+h.*t2.*t6.*t7.*t8.*t10-h.*t2.*t3.*t8.*t11.*t13,-e.*t11+h.*t2-a.*t2.*t11-f.*t2.*t7-h.*t2.*t13+h.*t2.*t12.*t13-h.*t5.*t6.*t7.*t8.*t10+h.*t3.*t5.*t8.*t11.*t13,e.*t5.*t7-h.*t3.*t7.*t8.*t13-h.*t6.*t8.*t10.*t11,0.0,0.0,1.0,0.0,e,0.0,0.0,0.0,0.0,-t3.*t5.*t9+t2.*t4.*t6.*t7+t4.*t5.*t8.*t10+t2.*t8.*t9.*t11+t2.*t3.*t4.*t10.*t11,-t2.*t3.*t9-t4.*t5.*t6.*t7+t2.*t4.*t8.*t10-t5.*t8.*t9.*t11-t3.*t4.*t5.*t10.*t11,-t4.*t6.*t11+t7.*t8.*t9+t3.*t4.*t7.*t10,0.0];
mt4 = [0.0,0.0,t3.*t4.*t5+t2.*t6.*t7.*t9-t2.*t4.*t8.*t11+t5.*t8.*t9.*t10+t2.*t3.*t9.*t10.*t11,t2.*t3.*t4-t5.*t6.*t7.*t9+t4.*t5.*t8.*t11+t2.*t8.*t9.*t10-t3.*t5.*t9.*t10.*t11,-t4.*t7.*t8-t6.*t9.*t11+t3.*t7.*t9.*t10];
Mp = reshape([mt1,mt2,mt3,mt4],6,6);
