function fp = motorcycleKinematicsForcingVector(in1,in2,in3)
%motorcycleKinematicsForcingVector
%    FP = motorcycleKinematicsForcingVector(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Sep-2024 18:26:17

omega_x = in2(1,:);
omega_y = in2(2,:);
omega_z = in2(3,:);
v_x = in2(4,:);
v_y = in2(5,:);
v_z = in2(6,:);
fp = [omega_x;omega_y;omega_z;v_x;v_y;v_z];
