function fun = slidingMassPMP(in1,m)
%slidingMassPMP
%    FUN = slidingMassPMP(IN1,M)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Jan-2024 13:27:35

lambda_1 = in1(3,:);
lambda_2 = in1(4,:);
r = in1(5,:);
v = in1(2,:);
fun = [r.*v;-lambda_2.*1.0./m.^2.*r;0.0;-lambda_1.*r;0.0];
