function pmp_eqs = slidingMassPMP(in1,m)
%slidingMassPMP
%    PMP_EQS = slidingMassPMP(IN1,M)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Jan-2024 15:30:59

lambda_1 = in1(3,:);
lambda_2 = in1(4,:);
v = in1(2,:);
pmp_eqs = [v;-lambda_2.*1.0./m.^2;0.0;-lambda_1];
