function out1 = slidingMassOptimalControl(in1,m)
%slidingMassOptimalControl
%    OUT1 = slidingMassOptimalControl(IN1,M)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Jan-2024 15:30:58

lambda_2 = in1(4,:);
out1 = -lambda_2./m;
