function out1 = slidingMass(in1,F_x,m)
%slidingMass
%    OUT1 = slidingMass(IN1,F_x,M)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Feb-2024 15:45:27

%    states = [p v]
%    inputs = [F_x]
%    params = [m]
%
v = in1(2,:);
out1 = [v;F_x./m];
