function G = prydeMotoLateralSSInputMatrix(in1)
%prydeMotoLateralSSInputMatrix
%    G = prydeMotoLateralSSInputMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    02-Mar-2026 15:45:54

%   states = [gamma y_w varphi delta omega_bz v_ry omega_bx v_l omega_varphi omega_delta alpha_r alpha_f]
%   inputs = [f_w tau_varphi tau_delta]
%   params = [C_delta C_l C_varphi I_bxx I_bxz I_bzz I_hxx I_hzz I_lxx I_lzz I_uxx I_uxz I_uzz K_xkf K_xkr K_yaf K_yar K_ygf K_ygr K_zaf K_zar K_zgf K_zgr R_f R_r V a_n b b_l b_w e f_d f_l f_zf f_zr g h h_l h_u h_w i_fy i_ry j k k_l k_varphi l_x m_b m_f m_h m_l m_r m_u nu omega_f0 omega_r0 p rho_f rho_r sigma_alpha_f sigma_alpha_r sigma_kappa_f sigma_kappa_r t_f t_r tau_p varepsilon]
%
R_r = in1(25,:);
b_l = in1(29,:);
h_l = in1(38,:);
G = reshape([0.0,0.0,0.0,0.0,-b_l,-1.0,-R_r+h_l,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0],[12,3]);
end
