function M = prydeMotoLateralSSMassMatrix(in1)
%prydeMotoLateralSSMassMatrix
%    M = prydeMotoLateralSSMassMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Mar-2026 13:42:37

%   states = [gamma delta omega_bz v_ry omega_bx omega_delta alpha_r alpha_f]
%   inputs = [tau_delta]
%   params = [C_delta I_bxx I_bxz I_bzz I_hxx I_hzz K_xkf K_xkr K_yaf K_yar K_ygf K_ygr K_zaf K_zar K_zgf K_zgr R_f R_r V a_n b e f_d f_l f_zf f_zr g h i_fy i_ry j k l_x m_b m_f m_h m_r omega_f0 omega_r0 p rho_f rho_r sigma_alpha_f sigma_alpha_r sigma_kappa_f sigma_kappa_r t_f t_r tau_p varepsilon]
%
I_bxx = in1(2,:);
I_bxz = in1(3,:);
I_bzz = in1(4,:);
I_hxx = in1(5,:);
I_hzz = in1(6,:);
R_f = in1(17,:);
R_r = in1(18,:);
b = in1(21,:);
e = in1(22,:);
h = in1(28,:);
j = in1(31,:);
k = in1(32,:);
l_x = in1(33,:);
m_b = in1(34,:);
m_f = in1(35,:);
m_h = in1(36,:);
m_r = in1(37,:);
p = in1(40,:);
sigma_alpha_f = in1(43,:);
sigma_alpha_r = in1(44,:);
varepsilon = in1(50,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = b+k;
t5 = b.*m_b;
t6 = e.*m_h;
t7 = l_x.*m_f;
t8 = m_f.*p;
t9 = varepsilon.*2.0;
t15 = -R_r;
t16 = -h;
t17 = -j;
t10 = sin(t9);
t11 = t3.^2;
t12 = I_hzz.*t2;
t13 = I_hzz.*t3;
t14 = p.*t7;
t18 = m_h.*t4;
t19 = t4.*t6;
t20 = R_f+t15;
t21 = R_r+t16;
t22 = R_r+t17;
t25 = t6+t7;
t23 = -t13;
t24 = t11-1.0;
t26 = m_f.*t20;
t27 = m_b.*t21;
t28 = m_h.*t22;
t29 = t7.*t20;
t30 = t8.*t20;
t31 = t5.*t21;
t32 = t6.*t22;
t33 = (I_hxx.*t10)./2.0;
t34 = (I_hzz.*t10)./2.0;
t37 = t18.*t22;
t40 = t5+t8+t18;
t41 = t12+t14+t19;
t35 = -t26;
t36 = -t34;
t38 = -t29;
t39 = -t30;
t42 = t27+t28+t35;
t43 = t23+t32+t38;
t44 = I_bxz+t31+t33+t36+t37+t39;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,I_bzz+I_hxx.*t11-I_hzz.*t24+b.*t5+p.*t8+t4.*t18,t40,t44,t41,0.0,0.0,0.0,0.0,t40,m_b+m_f+m_h+m_r,t42,t25,0.0,0.0,0.0,0.0,t44,t42,I_bxx+I_hzz.*t11-I_hxx.*t24+t20.*t26+t21.*t27+t22.*t28,t43,0.0,0.0,0.0,0.0,t41,t25,t43,I_hzz+e.*t6+l_x.*t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sigma_alpha_r,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sigma_alpha_f],[8,8]);
end
