function M = sharpMotorcycleSSMassMatrix(in1)
%sharpMotorcycleSSMassMatrix
%    M = sharpMotorcycleSSMassMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Feb-2026 17:37:28

%   states = [varphi delta omega_psi v_y omega_varphi omega_delta Y_r Y_f]
%   inputs = [tau_delta]
%   params = [C_delta C_f1 C_f2 C_r1 C_r2 C_rxz I_fx I_fz I_rx I_rz V Z_f a a_n b e f g h i_fy i_ry j k m_f m_r r_f r_r sigma varepsilon]
%
C_rxz = in1(6,:);
I_fx = in1(7,:);
I_fz = in1(8,:);
I_rx = in1(9,:);
I_rz = in1(10,:);
e = in1(16,:);
h = in1(19,:);
j = in1(22,:);
k = in1(23,:);
m_f = in1(24,:);
m_r = in1(25,:);
sigma = in1(28,:);
varepsilon = in1(29,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = e.*m_f;
t5 = h.*m_r;
t6 = j.*m_f;
t7 = k.*m_f;
t8 = varepsilon.*2.0;
t16 = -C_rxz;
t17 = -I_fz;
t9 = sin(t8);
t10 = t3.^2;
t11 = I_fz.*t2;
t12 = I_fz.*t3;
t13 = j.*t4;
t14 = k.*t4;
t15 = k.*t6;
t18 = -t4;
t19 = -t5;
t20 = -t6;
t21 = -t7;
t22 = -t11;
t23 = -t12;
t24 = -t13;
t25 = -t14;
t26 = -t15;
t27 = I_fx.*t10;
t28 = I_fz.*t10;
t29 = (I_fx.*t9)./2.0;
t30 = (I_fz.*t9)./2.0;
t32 = t19+t20;
t31 = -t30;
t33 = t22+t25;
t34 = t23+t24;
t35 = t16+t26+t29+t31;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-I_rz+t17-t27+t28+k.*t21,t21,t35,t33,0.0,0.0,0.0,0.0,t21,-m_f-m_r,t32,t18,0.0,0.0,0.0,0.0,t35,t32,-I_fx-I_rx+t27+h.*t19+j.*t20+t10.*t17,t34,0.0,0.0,0.0,0.0,t33,t18,t34,t17+e.*t18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sigma,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sigma],[8,8]);
end
