function H = sharpMotorcycleSSForcingMatrix(in1)
%sharpMotorcycleSSForcingMatrix
%    H = sharpMotorcycleSSForcingMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Feb-2026 17:37:28

%   states = [varphi delta omega_psi v_y omega_varphi omega_delta Y_r Y_f]
%   inputs = [tau_delta]
%   params = [C_delta C_f1 C_f2 C_r1 C_r2 C_rxz I_fx I_fz I_rx I_rz V Z_f a a_n b e f g h i_fy i_ry j k m_f m_r r_f r_r sigma varepsilon]
%
C_delta = in1(1,:);
C_f1 = in1(2,:);
C_f2 = in1(3,:);
C_r1 = in1(4,:);
C_r2 = in1(5,:);
V = in1(11,:);
Z_f = in1(12,:);
a = in1(13,:);
a_n = in1(14,:);
b = in1(15,:);
e = in1(16,:);
g = in1(18,:);
h = in1(19,:);
i_fy = in1(20,:);
i_ry = in1(21,:);
j = in1(22,:);
k = in1(23,:);
m_f = in1(24,:);
m_r = in1(25,:);
r_f = in1(26,:);
r_r = in1(27,:);
varepsilon = in1(29,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = Z_f.*a_n;
t5 = e.*g.*m_f;
t6 = -V;
t7 = -a_n;
t8 = 1.0./r_f;
t9 = 1.0./r_r;
t10 = 1.0./t2;
t11 = a+t7;
t12 = -t5;
t13 = V.*i_fy.*t8;
t14 = V.*i_ry.*t9;
t15 = t2.*t13;
t16 = t3.*t13;
t17 = t4+t12;
H = reshape([0.0,0.0,0.0,0.0,-g.*h.*m_r-g.*j.*m_f,t17,C_r2.*V,C_f2.*V,0.0,0.0,0.0,0.0,t17,t3.*t4+t3.*t12,0.0,C_f1.*V.*t2+C_f2.*V.*t3,0.0,0.0,V.*k.*m_f,V.*m_f+V.*m_r,t13+t14+V.*h.*m_r+V.*j.*m_f,t16+V.*e.*m_f,C_r1.*b,-C_f1.*t10.*t11,0.0,0.0,0.0,0.0,0.0,0.0,-C_r1,-C_f1,1.0,0.0,i_fy.*t6.*t8+i_ry.*t6.*t9,0.0,0.0,i_fy.*t2.*t6.*t8,0.0,0.0,0.0,1.0,i_fy.*t3.*t6.*t8,0.0,t15,C_delta,0.0,C_f1.*a_n,0.0,0.0,b,-1.0,0.0,0.0,t6,0.0,0.0,0.0,-t10.*t11,-1.0,0.0,a_n,0.0,t6],[8,8]);
end
