function Gsharp = extendedSharpMotorcycleLinearizedInputMatrix(V,in2)
%extendedSharpMotorcycleLinearizedInputMatrix
%    Gsharp = extendedSharpMotorcycleLinearizedInputMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    14-Jun-2024 12:45:16

Gsharp = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[9,2]);
