function Gsharp = extendedSharpMotorcycleLinearizedInputMatrix(V,in2)
%extendedSharpMotorcycleLinearizedInputMatrix
%    Gsharp = extendedSharpMotorcycleLinearizedInputMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-Jun-2024 14:17:10

Gsharp = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[10,2]);
