function Hsharp = extendedSharpMotorcycleLinearizedForcingMatrix(V,in2)
%extendedSharpMotorcycleLinearizedForcingMatrix
%    Hsharp = extendedSharpMotorcycleLinearizedForcingMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-Jun-2024 14:17:10

C_delta = in2(1,:);
C_f1 = in2(2,:);
C_f2 = in2(3,:);
C_r1 = in2(4,:);
C_r2 = in2(5,:);
Z_f = in2(14,:);
a = in2(15,:);
a_n = in2(16,:);
b = in2(17,:);
beta = in2(18,:);
c = in2(19,:);
e = in2(20,:);
g = in2(21,:);
h = in2(22,:);
i_fy = in2(23,:);
i_ry = in2(24,:);
j = in2(25,:);
k = in2(26,:);
m_f = in2(27,:);
m_r = in2(28,:);
m_u = in2(29,:);
p = in2(30,:);
r = in2(31,:);
r_f = in2(32,:);
r_r = in2(33,:);
varepsilon = in2(35,:);
t2 = cos(beta);
t3 = cos(varepsilon);
t4 = sin(varepsilon);
t5 = Z_f.*a_n;
t6 = e.*g.*m_f;
t7 = g.*m_u.*r;
t8 = -V;
t9 = -a_n;
t10 = 1.0./r_f;
t11 = 1.0./r_r;
t12 = -t5;
t13 = 1.0./t3;
t14 = a+t9;
t15 = V.*i_fy.*t10;
t16 = V.*i_ry.*t11;
t17 = t3.*t15;
t18 = t4.*t15;
t19 = t6+t12;
mt1 = [0.0,0.0,0.0,0.0,0.0,g.*(h.*m_r+j.*m_f+m_u.*p+m_u.*r.*t2),t7,t19,C_r2.*V,C_f2.*V,0.0,0.0,0.0,0.0,0.0,t7,t2.*t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t19,0.0,-t4.*(t5-t6),0.0,V.*(C_f1.*t3+C_f2.*t4),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-C_r1,-C_f1,0.0,0.0,0.0,t8.*(m_f+m_r+m_u),V.*(c.*m_u-k.*m_f+m_u.*r.*sin(beta)),h.*m_r.*t8+j.*m_f.*t8+i_fy.*t8.*t10+i_ry.*t8.*t11+m_u.*p.*t8+m_u.*r.*t2.*t8,m_u.*r.*t8,e.*m_f.*t8+i_fy.*t4.*t8.*t10,C_r1.*b,-C_f1.*t13.*t14,1.0,0.0,0.0,0.0,t15+t16,0.0,0.0,t17,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,t18,i_fy.*t3.*t8.*t10,0.0,-C_delta,0.0,C_f1.*a_n,0.0];
mt2 = [0.0,0.0,1.0,-b,0.0,0.0,0.0,t8,0.0,0.0,0.0,0.0,1.0,t13.*t14,0.0,0.0,t9,0.0,t8];
Hsharp = reshape([mt1,mt2],10,10);
