function Gsharp = sharpMotorcycleLinearizedInputMatrix(V,in2)
%sharpMotorcycleLinearizedInputMatrix
%    Gsharp = sharpMotorcycleLinearizedInputMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Jun-2024 17:47:45

Gsharp = [0.0;0.0;0.0;0.0;0.0;1.0;0.0;0.0];
