function out1 = inputMatrix(in1)
%inputMatrix
%    OUT1 = inputMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Mar-2025 09:36:00

V = in1(:,3);
p = in1(:,2);
varepsilon = in1(:,1);
out1 = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-p./(V.*cos(varepsilon)),0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[10,6]);
end
