function Gr = prydeMotorcycleLinearizedInputMatrix(V,in2)
%prydeMotorcycleLinearizedInputMatrix
%    Gr = prydeMotorcycleLinearizedInputMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    21-Jun-2024 19:28:12

Gr = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[8,2]);
