function Hr = prydeMotorcycleLinearizedForcingMatrix(V,in2)
%prydeMotorcycleLinearizedForcingMatrix
%    Hr = prydeMotorcycleLinearizedForcingMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    21-Jun-2024 19:28:12

C_delta = in2(1,:);
C_f1 = in2(2,:);
C_f2 = in2(3,:);
C_r1 = in2(4,:);
C_r2 = in2(5,:);
a = in2(12,:);
a_n = in2(13,:);
b = in2(14,:);
e = in2(15,:);
g = in2(16,:);
h = in2(17,:);
i_fy = in2(18,:);
i_ry = in2(19,:);
j = in2(20,:);
k = in2(21,:);
m_f = in2(22,:);
m_r = in2(23,:);
r_f = in2(24,:);
r_r = in2(25,:);
varepsilon = in2(27,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = varepsilon.*2.0;
t6 = a.*e.*m_f;
t7 = a_n.*e.*m_f;
t9 = -V;
t10 = -a_n;
t11 = 1.0./r_f;
t12 = 1.0./r_r;
t5 = sin(t4);
t8 = b.*t2;
t13 = 1.0./t2;
t17 = a_n.*k.*m_f.*t2;
t18 = -t7;
t19 = V.*i_fy.*t11;
t20 = V.*i_ry.*t12;
t14 = a_n.*m_f.*t8;
t15 = a_n.*m_r.*t8;
t16 = e.*m_f.*t8;
t21 = t2.*t19;
t22 = t3.*t19;
t23 = a+t8+t10;
t24 = 1.0./t23;
t25 = t6+t14+t15+t16+t17+t18;
t26 = g.*t24.*t25;
mt1 = [0.0,0.0,0.0,0.0,g.*(h.*m_r+j.*m_f),t26,C_r2.*V,C_f2.*V,0.0,0.0,0.0,0.0,t26,(g.*(t3.*t7.*-2.0-e.^2.*m_f.*t3.*2.0+e.*j.*m_f+a_n.*b.*m_f.*t5+a_n.*b.*m_r.*t5+b.*e.*m_f.*t5+a_n.*k.*m_f.*t5+e.*k.*m_f.*t5-e.*j.*m_f.*cos(t4)))./(a.*2.0-a_n.*2.0+t8.*2.0),0.0,V.*(C_f1.*t2+C_f2.*t3),0.0,0.0,0.0,0.0,0.0,0.0,-C_r1,-C_f1,0.0,0.0,t9.*(m_f+m_r),t9.*(b.*m_f+b.*m_r+k.*m_f),h.*m_r.*t9+j.*m_f.*t9+i_fy.*t9.*t11+i_ry.*t9.*t12,e.*m_f.*t9+i_fy.*t3.*t9.*t11,0.0,-C_f1.*t13.*t23,1.0,0.0,0.0,t19+t20,0.0,t21,0.0,0.0,0.0,1.0,0.0,t22,i_fy.*t2.*t9.*t11,-C_delta,0.0,C_f1.*a_n,0.0,0.0,1.0,0.0];
mt2 = [0.0,0.0,t9,0.0,0.0,0.0,1.0,t13.*t23,0.0,t10,0.0,t9];
Hr = reshape([mt1,mt2],8,8);
