function p = bikeSimGeometricParameters()
    p.RearCrownRadius = 0;
    p.RearRadius = 0;
    p.Trim = 0;
    p.SwingArmOffset = 0;
    p.Wheelbase = 0;
    p.FrontRadius = 0;
    p.Caster = 0;
    p.Rake = 0;
    p.ForkLength = 0;
    p.HandlebarOffset = 0;
    p.HandlebarHeight = 0;
    p.RiderLean = 0;
    p.RiderWidth = 0;
    p.RiderDepth = 0;
    p.StepOffset = 0;
    p.StepHeight = 0;
    p.ShinHeight = 0;
    p.ThighLength = 0;
    p.LegHeight = 0;
    p.BackHeight = 0;
end