function Jg = camberJacobian(in1)
%camberJacobian
%    Jg = camberJacobian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    17-Oct-2025 04:23:57

varepsilon = in1(60,:);
Jg = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,-sin(varepsilon),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,9]);
end
