function Jacf = centAccelJacobian(in1)
%centAccelJacobian
%    Jacf = centAccelJacobian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Sep-2025 23:13:28

V = in1(17,:);
varepsilon = in1(62,:);
Jacf = [0.0,0.0,0.0,0.0,0.0,V,0.0,0.0,V.*cos(varepsilon)];
end
