function J = frontContactConstraintJac(delta,in2,in3)
%frontContactConstraintJac
%    J = frontContactConstraintJac(DELTA,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    31-May-2025 03:55:39

l_x = in3(:,3);
rho_f = in3(:,5);
theta = in2(:,2);
varphi = in2(:,1);
varepsilon = in3(:,9);
t2 = cos(delta);
t3 = sin(delta);
t4 = cos(theta);
t5 = cos(varphi);
t6 = cos(varepsilon);
t7 = sin(theta);
t8 = sin(varphi);
t9 = sin(varepsilon);
t10 = t2.^2;
t11 = t3.^2;
t12 = t4.^2;
t13 = t5.^2;
t14 = t6.^2;
t15 = t2.*t3.*2.0;
t40 = t2.*t3.*t5.*t6.*t7.*t8.*-2.0;
t16 = -t10;
t17 = t10.*t13;
t18 = t12.*t13;
t19 = t13.*t14;
t20 = t13.*t15;
t21 = t2.*t3.*t13.*-2.0;
t27 = t4.*t5.*t8.*t9.*t10.*2.0;
t28 = t5.*t6.*t7.*t8.*t10.*2.0;
t29 = t4.*t5.*t8.*t9.*t11.*2.0;
t30 = t5.*t6.*t7.*t8.*t11.*2.0;
t31 = t4.*t6.*t7.*t9.*t13.*2.0;
t34 = t4.*t5.*t8.*t9.*t15;
t44 = t2.*t3.*t4.*t6.*t7.*t9.*t13.*4.0;
t22 = -t18;
t23 = -t19;
t24 = t12.*t17;
t25 = t14.*t17;
t26 = t14.*t18.*2.0;
t32 = t15.*t18;
t33 = t15.*t19;
t36 = -t28;
t37 = -t29;
t38 = t2.*t3.*t18.*-2.0;
t39 = t2.*t3.*t19.*-2.0;
t42 = t4.*t6.*t7.*t9.*t17.*2.0;
t43 = t2.*t3.*t14.*t18.*4.0;
t41 = t14.*t24.*2.0;
t46 = -t42;
t47 = t15+t21+t27+t30+t36+t37+t38+t39+t43+t44;
t45 = -t41;
t48 = t16+t17+t22+t23+t24+t25+t26+t31+t34+t40+t45+t46+1.0;
t49 = 1.0./sqrt(t48);
t50 = t49.^3;
J = l_x.*t2.*t8+rho_f.*t20.*t49+rho_f.*t28.*t49+rho_f.*t29.*t49+rho_f.*t32.*t49+rho_f.*t33.*t49+(rho_f.*t47.*t50)./2.0-rho_f.*t2.*t3.*t49.*2.0-(rho_f.*t10.*t47.*t50)./2.0+(rho_f.*t17.*t47.*t50)./2.0-(rho_f.*t18.*t47.*t50)./2.0-(rho_f.*t19.*t47.*t50)./2.0+(rho_f.*t24.*t47.*t50)./2.0+(rho_f.*t25.*t47.*t50)./2.0-l_x.*t3.*t4.*t5.*t9+l_x.*t3.*t5.*t6.*t7+rho_f.*t14.*t18.*t47.*t50-rho_f.*t2.*t3.*t14.*t18.*t49.*4.0+rho_f.*t14.*t16.*t18.*t47.*t50-rho_f.*t4.*t5.*t8.*t9.*t10.*t49.*2.0-rho_f.*t5.*t6.*t7.*t8.*t11.*t49.*2.0+rho_f.*t4.*t6.*t7.*t9.*t13.*t47.*t50-rho_f.*t2.*t3.*t4.*t6.*t7.*t9.*t13.*t49.*4.0+rho_f.*t2.*t3.*t4.*t5.*t8.*t9.*t47.*t50-rho_f.*t2.*t3.*t5.*t6.*t7.*t8.*t47.*t50+rho_f.*t4.*t6.*t7.*t9.*t13.*t16.*t47.*t50;
end
