function out1 = normalForcesAtTrim(in1)
%normalForcesAtTrim
%    OUT1 = normalForcesAtTrim(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Apr-2025 13:01:00

g = in1(:,23);
m_b = in1(:,27);
m_h = in1(:,28);
out1 = [-g.*(m_b+m_h);0.0];
end
