function Gr = prydeMotorcycleLinearizedInputMatrix(V,in2)
%prydeMotorcycleLinearizedInputMatrix
%    Gr = prydeMotorcycleLinearizedInputMatrix(V,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    26-Jun-2024 14:17:04

Gr = [0.0;0.0;0.0;0.0;0.0;1.0];
