function rear_tire_eqns = rearTireEqns(in1)
%rearTireEqns
%    REAR_TIRE_EQNS = rearTireEqns(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    17-Oct-2025 04:23:57

A = in1(1,:);
C_l = in1(4,:);
C_p = in1(5,:);
V = in1(15,:);
a = in1(16,:);
a_n = in1(17,:);
b = in1(18,:);
e = in1(19,:);
f = in1(20,:);
f_zr0 = in1(22,:);
g = in1(23,:);
m_b = in1(27,:);
m_h = in1(29,:);
m_r = in1(30,:);
p_Kxr1 = in1(39,:);
p_Kxr2 = in1(40,:);
p_Kyr1 = in1(41,:);
p_Kxr3 = in1(42,:);
p_Kyr2 = in1(43,:);
p_Kyr3 = in1(44,:);
p_Kyr6 = in1(45,:);
p_Kyr7 = in1(46,:);
q_dzr1 = in1(51,:);
q_dzr2 = in1(52,:);
q_dzr8 = in1(53,:);
q_dzr9 = in1(54,:);
rho = in1(55,:);
t_r = in1(59,:);
varepsilon = in1(60,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = g.*m_r;
t5 = V.^2;
t10 = -a_n;
t12 = 1.0./f_zr0;
t13 = 1.0./p_Kyr3;
t6 = a.*t2;
t7 = b.*t2;
t8 = e.*t2;
t9 = f.*t3;
t14 = 1.0./t2;
t15 = a+t10;
t18 = (A.*C_l.*rho.*t5)./4.0;
t19 = (A.*C_p.*rho.*t5)./2.0;
t20 = t7+t15;
t21 = -t18;
t22 = t14.*t15;
t23 = 1.0./t20;
t24 = g.*m_b.*t15.*t23;
t26 = -g.*m_h.*t2.*t23.*(t6+t8-t9-t22);
t27 = t4+t19+t21+t24+t26;
t29 = t12.*t13.*t27;
t30 = atan(t29);
t31 = p_Kyr2.*t30;
t32 = sin(t31);
mt1 = [t27;t27.*exp(-p_Kxr3.*t12.*(f_zr0-t4+t18-t19-t24+g.*m_h.*t2.*t23.*(t6+t8-t9-t22))).*(p_Kxr1-p_Kxr2.*t12.*(f_zr0-t4+t18-t19-t24+g.*m_h.*t2.*t23.*(t6+t8-t9-t22)));f_zr0.*p_Kyr1.*t32;t27.*(p_Kyr6-p_Kyr7.*t12.*(f_zr0-t4+t18-t19-t24+g.*m_h.*t2.*t23.*(t6+t8-t9-t22)));-p_Kyr1.*t27.*t32.*t_r.*(q_dzr1-q_dzr2.*t12.*(f_zr0-t4+t18-t19-t24+g.*m_h.*t2.*t23.*(t6+t8-t9-t22)))];
mt2 = [t27.*t_r.*(q_dzr8-q_dzr9.*t12.*(f_zr0-t4+t18-t19-t24+g.*m_h.*t2.*t23.*(t6+t8-t9-t22)))];
rear_tire_eqns = [mt1;mt2];
end
