function out1 = rollingDiskNonminimalCoordinates(in1,in2,in3)
%rollingDiskNonminimalCoordinates
%    OUT1 = rollingDiskNonminimalCoordinates(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Jan-2024 03:34:57

%    states = [x y z psi varphi theta u_1 u_2 u_3]
%    inputs = []
%    params = [g m r]
%
g = in3(:,1);
m = in3(:,2);
psi = in1(4,:);
r = in3(:,3);
u_1 = in1(7,:);
u_2 = in1(8,:);
u_3 = in1(9,:);
varphi = in1(5,:);
t2 = cos(psi);
t3 = cos(varphi);
t4 = sin(psi);
t5 = sin(varphi);
t6 = m.^2;
t7 = r.^2;
t9 = varphi.*2.0;
t8 = t7.^2;
t10 = sin(t9);
t11 = t5.^2;
t12 = t3.*u_3.*2.0;
t14 = (m.*t7)./4.0;
t13 = t10.*u_1.*5.0;
t15 = m.*t7.*t11.*(5.0./4.0);
t17 = t6.*t8.*t11.*(9.0./4.0);
t16 = t12+t13;
t18 = t14+t15;
t19 = m.*t7.*t18.*(3.0./2.0);
t20 = -t19;
t21 = t17+t20;
t22 = 1.0./t21;
out1 = [-r.*t2.*u_3-r.*t2.*t5.*u_1-r.*t3.*t4.*u_2;-r.*t4.*u_3+r.*t2.*t3.*u_2-r.*t4.*t5.*u_1;r.*t5.*u_2;u_1;u_2;u_3;t6.*t8.*t16.*t22.*u_2.*(3.0./8.0)-t3.*t5.*t6.*t8.*t22.*u_1.*u_2.*(1.5e+1./4.0);((g.*m.*r.*t5+m.*t3.*t7.*u_1.*u_3.*(3.0./2.0)+m.*t3.*t5.*t7.*u_1.^2.*(5.0./4.0)).*(4.0./5.0))./(m.*t7);t5.*t6.*t8.*t16.*t22.*u_2.*(-3.0./8.0)+m.*t3.*t7.*t18.*t22.*u_1.*u_2.*(5.0./2.0)];
