function G = prydeMotorcycleNoSlipSSInputMatrix(in1)
%prydeMotorcycleNoSlipSSInputMatrix
%    G = prydeMotorcycleNoSlipSSInputMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Oct-2025 22:00:27

%   states = [varphi delta omega_bz v_rx omega_bx]
%   inputs = [f_x tau_delta]
%   params = [A C_d C_delta C_l C_p I_bxx I_bxz I_bzz I_hxx I_hzz K_ycf K_ycr K_yvf K_yvr V a a_n b e f f_zf0 f_zr0 g h i_fy i_ry m_b m_f m_h m_r p_Kxf1 p_Kxf2 p_Kyf1 p_Kxf3 p_Kyf2 p_Kyf3 p_Kyf6 p_Kyf7 p_Kxr1 p_Kxr2 p_Kyr1 p_Kxr3 p_Kyr2 p_Kyr3 p_Kyr6 p_Kyr7 q_dzf1 q_dzf2 q_dzf8 q_dzf9 q_dzr1 q_dzr2 q_dzr8 q_dzr9 rho rho_f rho_r t_f t_r varepsilon]
%
a = in1(16,:);
a_n = in1(17,:);
b = in1(18,:);
h = in1(24,:);
rho_r = in1(57,:);
t_r = in1(59,:);
varepsilon = in1(60,:);
t2 = cos(varepsilon);
G = reshape([0.0,0.0,0.0,-h./(rho_r+t_r),0.0,0.0,0.0,-(a-a_n+b.*t2)./(a_n.*t2),0.0,0.0],[5,2]);
end
