function f0 = invertedPendulumAndCartBody2DynamicsCentrifugalForcingVector(in1,in2)
%invertedPendulumAndCartBody2DynamicsCentrifugalForcingVector
%    F0 = invertedPendulumAndCartBody2DynamicsCentrifugalForcingVector(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Sep-2025 20:08:34

%   states = [x theta v omega]
%   inputs = [F_x]
%   params = [I_yy b_theta b_x g l m_c m_p]
%
l = in2(5,:);
m_p = in2(7,:);
omega = in1(4,:);
theta = in1(2,:);
v = in1(3,:);
f0 = [0.0;-l.*m_p.*omega.*v.*sin(theta)];
end
