function M = invertedPendulumAndCartBody2DynamicsMassMatrix(in1,in2)
%invertedPendulumAndCartBody2DynamicsMassMatrix
%    M = invertedPendulumAndCartBody2DynamicsMassMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Sep-2025 20:08:34

%   states = [x theta v omega]
%   inputs = [F_x]
%   params = [I_yy b_theta b_x g l m_c m_p]
%
I_yy = in2(1,:);
l = in2(5,:);
m_p = in2(7,:);
theta = in1(2,:);
t2 = cos(theta);
t3 = l.*m_p.*t2;
t4 = -t3;
M = reshape([m_p,t4,t4,I_yy+l.^2.*m_p],[2,2]);
end
