function f1 = invertedPendulumAndCartBody2DynamicsCoriolisForcingVector(in1,in2)
%invertedPendulumAndCartBody2DynamicsCoriolisForcingVector
%    F1 = invertedPendulumAndCartBody2DynamicsCoriolisForcingVector(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Sep-2025 20:08:35

%   states = [x theta v omega]
%   inputs = [F_x]
%   params = [I_yy b_theta b_x g l m_c m_p]
%
l = in2(5,:);
m_p = in2(7,:);
omega = in1(4,:);
theta = in1(2,:);
v = in1(3,:);
t2 = sin(theta);
f1 = [-l.*m_p.*omega.^2.*t2;l.*m_p.*omega.*t2.*v];
end
