function f2 = invertedPendulumAndCartBody2DynamicsActiveForcingVector(in1,F_x,in3)
%invertedPendulumAndCartBody2DynamicsActiveForcingVector
%    F2 = invertedPendulumAndCartBody2DynamicsActiveForcingVector(IN1,F_x,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Sep-2025 20:08:35

%   states = [x theta v omega]
%   inputs = [F_x]
%   params = [I_yy b_theta b_x g l m_c m_p]
%
b_theta = in3(2,:);
g = in3(4,:);
l = in3(5,:);
m_p = in3(7,:);
omega = in1(4,:);
theta = in1(2,:);
f2 = [0.0;-b_theta.*omega-g.*l.*m_p.*sin(theta)];
end
