function solfz = sharpMotorcycleTrimNormalForces(in1)
%sharpMotorcycleTrimNormalForces
%    SOLFZ = sharpMotorcycleTrimNormalForces(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Feb-2026 17:37:29

a = in1(13,:);
a_n = in1(14,:);
b = in1(15,:);
e = in1(16,:);
f = in1(17,:);
g = in1(18,:);
j = in1(22,:);
k = in1(23,:);
m_f = in1(24,:);
m_r = in1(25,:);
varepsilon = in1(29,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t9 = -a_n;
t10 = -e;
t4 = t2.^2;
t5 = t2.^3;
t6 = b.*t2;
t7 = k.*t2;
t8 = j.*t3;
t11 = k.*t5;
t12 = a.*t4;
t13 = e.*t4;
t15 = t4.*t8;
t14 = -t11;
t16 = -t15;
t17 = t6+t7+t8+t9+t10+t12+t13+t14+t16;
t18 = 1.0./t17;
solfz = [-g.*t2.*t18.*(b.*m_f+b.*m_r+a.*m_f.*t2+e.*m_f.*t2+f.*m_f.*t3);g.*t18.*(a_n.*m_f+a_n.*m_r+e.*m_f+e.*m_r-m_f.*t7-m_f.*t8+m_f.*t11+m_f.*t15-m_r.*t7-m_r.*t8+m_r.*t11-m_r.*t12+m_r.*t15+m_r.*t4.*t10+f.*m_f.*t2.*t3)];
end
