close("all"); clear; clc;
setmadsympath();

r = 0.227;
t = 0.07;
m = 14.7;
Ixx = m*(5*r^2 + 4*t^2)/8;
Iyy = m*(4*r^2 + 3*t^2)/4;
Izz = Ixx;

bs = bigSportsParameters();
pr = struct2array(table2struct(bs.RearTire.Pacejka))';
tr = bs.RearTire.UndeflectedCrownRadius;
Lx = bs.RearTire.LongitudinalRelaxationLength;
Ly = bs.RearTire.LateralRelaxationLength;
Rr = bs.RearTire.EffectiveRollingRadius;
Vlow = 5/3.6;
vx = 0/3.6;

rt = simscape.multibody.tirread("rear_tire.tir");
rear_tire = tireModel.import("rear_tire.tir");
td = tireData();
td.NominalFz = rt.VERTICAL.FNOMIN;
td.Fx = 0;
td.Fy = 0;
td.Fz = rt.VERTICAL_FORCE_RANGE.FZMIN;
td.Mx = 0;
td.My = 0;
td.Mz = 0;
td.V = 0;
td.Vx = 0;
td.Vy = 0;
td.omega = 0;
td.psidot = 0;
td.kappa = 0;
td.gamma = 0;
td.Tw = 0;
td.IP = rt.OPERATING_CONDITIONS.INFLPRES;
td.NominalIP = rt.OPERATING_CONDITIONS.NOMPRES;
res = rear_tire.compute(td);
z0 = res.Re;