function out1 = featureMononomialBasis(x,y)
%featureMononomialBasis
%    OUT1 = featureMononomialBasis(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    29-Jun-2025 23:41:36

t2 = x.*y;
t3 = x.^2;
t4 = y.^2;
out1 = reshape([t3,0.0,t2,0.0,x,0.0,t4,0.0,y,0.0,1.0,0.0,0.0,t3,0.0,t2,0.0,x,0.0,t4,0.0,y,0.0,1.0],[2,12]);
end
