function out1 = featureVelocityJacobian(f,c_x,c_y,n_x,n_y,n_z,d)
%featureVelocityJacobian
%    OUT1 = featureVelocityJacobian(F,C_X,C_Y,N_X,N_Y,N_Z,D)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    29-Jun-2025 23:41:36

t2 = c_x.*n_x;
t3 = c_y.*n_y;
t4 = f.*n_z;
t5 = 1.0./d;
t6 = 1.0./f;
t7 = -t4;
t8 = c_x.*t6;
t9 = c_y.*t6;
t10 = n_x.*t5;
t11 = n_y.*t5;
t12 = -t6;
t13 = c_y.*t8;
t14 = -t10;
t15 = -t11;
t16 = t6.*t10;
t17 = t6.*t11;
t18 = t2+t3+t7;
t19 = t5.*t18;
out1 = reshape([0.0,t6,-t9,0.0,-t8,t13,0.0,0.0,0.0,t6,t9.*-2.0,f+c_y.*t9,t12,0.0,t8.*2.0,0.0,0.0,-f-c_x.*t8,0.0,t12,t9,0.0,t8,-t13,0.0,0.0,0.0,0.0,1.0,-c_y,0.0,0.0,-1.0,0.0,0.0,c_x,0.0,0.0,t14,0.0,t15,t19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t14,0.0,t15,t19,t16,t17,t5.*t12.*(t2+t18),0.0,t8.*t15,t8.*t19,0.0,t16,t9.*t14,t17,t5.*t12.*(t3+t18),t9.*t19],[12,6]);
end
