function out1 = motoEgoMotionAngVelJac(f,in2,in3,in4,in5,in6)
%motoEgoMotionAngVelJac
%    OUT1 = motoEgoMotionAngVelJac(F,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-May-2025 11:12:35

gamma = in4(2,:);
h_c = in6(:,5);
mu = in6(:,1);
p = in6(:,4);
p_x = in3(1,:);
p_y = in3(2,:);
p_z = in3(3,:);
rho_r = in6(:,3);
theta = in4(3,:);
t2 = cos(gamma);
t3 = cos(mu);
t4 = cos(theta);
t5 = sin(gamma);
t6 = sin(mu);
t7 = sin(theta);
t8 = mu+theta;
t10 = 1.0./p_z;
t9 = cos(t8);
t11 = t10.^2;
t12 = 1.0./t2;
t13 = 1.0./t9;
out1 = reshape([-f.*p_x.*p_y.*t11,-f-t11.*t13.*(f.*p_y.^2.*t9+f.*p_z.*(h_c.*t7+p.*t4-rho_r.*t7)),f+f.*p_x.^2.*t11,f.*t11.*t13.*(p_x.*p_y.*t3.*t4-p_x.*p_y.*t6.*t7)-f.*t10.*t12.*t13.*(h_c.*t5.*t6-p.*t3.*t5-rho_r.*t5.*t6+rho_r.*t3.*t5.*t7+rho_r.*t4.*t5.*t6),-f.*p_y.*t10,f.*t10.*t13.*(p_x.*t3.*t4-p_x.*t6.*t7)+f.*t10.*t12.*t13.*(h_c.*t3.*t5+p.*t5.*t6-rho_r.*t3.*t5+rho_r.*t3.*t4.*t5-rho_r.*t5.*t6.*t7)],[2,3]);
end
