function out1 = motoEgoMotionMassMatrix(f,in2,in3,in4,in5,in6)
%motoEgoMotionMassMatrix
%    OUT1 = motoEgoMotionMassMatrix(F,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-May-2025 11:12:19

gamma = in4(2,:);
mu = in6(:,1);
p_x = in3(1,:);
p_y = in3(2,:);
p_z = in3(3,:);
theta = in4(3,:);
t2 = mu+theta;
t4 = 1.0./p_z;
t3 = cos(t2);
t5 = t4.^2;
t6 = 1.0./t3;
out1 = reshape([-f.*t4,(f.*t4.*t6.*sin(gamma))./cos(gamma),f.*p_x.*t5,f.*t5.*t6.*(p_y.*t3+p_z.*sin(t2))],[2,2]);
end
