function out1 = motoEgoMotionAngVelJac(in1,in2)
%motoEgoMotionAngVelJac
%    OUT1 = motoEgoMotionAngVelJac(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Jun-2025 17:36:45

f = in2(:,1);
gamma = in1(:,2);
h_c = in2(:,3);
mu = in2(:,2);
p = in2(:,4);
p_x = in1(:,4);
p_y = in1(:,5);
p_z = in1(:,6);
rho_r = in2(:,5);
theta = in1(:,3);
t2 = cos(gamma);
t3 = cos(mu);
t4 = cos(theta);
t5 = sin(gamma);
t6 = sin(mu);
t7 = sin(theta);
t8 = mu+theta;
t9 = p_x.^2;
t10 = p_z.^2;
t11 = sin(t8);
t12 = 1.0./t10;
t13 = 1.0./t2;
t14 = 1.0./t11;
mt1 = [f.*p_x.*t12.*t14.*(h_c.*t7+p.*t4-p_y.*t11-rho_r.*t7),-f.*t12.*t14.*(t10.*t11+p_y.^2.*t11-h_c.*p_y.*t7-p.*p_y.*t4+p_y.*rho_r.*t7),f.*t12.*t13.*t14.*(h_c.*p_x.*t5.*t6-p.*p_x.*t3.*t5-p_x.*rho_r.*t5.*t6+t2.*t3.*t7.*t9+t2.*t4.*t6.*t9+t2.*t3.*t7.*t10+t2.*t4.*t6.*t10+p_x.*rho_r.*t3.*t5.*t7+p_x.*rho_r.*t4.*t5.*t6),f.*p_y.*t12.*t13.*t14.*(h_c.*t5.*t6-p.*t3.*t5-rho_r.*t5.*t6+p_x.*t2.*t3.*t7+p_x.*t2.*t4.*t6+rho_r.*t3.*t5.*t7+rho_r.*t4.*t5.*t6)];
mt2 = [-f.*t12.*t13.*t14.*(h_c.*p_x.*t3.*t5+p.*p_x.*t5.*t6-p_x.*rho_r.*t3.*t5+p_y.*p_z.*t2.*t3.*t7+p_y.*p_z.*t2.*t4.*t6+p_x.*rho_r.*t3.*t4.*t5-p_x.*rho_r.*t5.*t6.*t7),f.*t12.*t13.*t14.*(-h_c.*p_y.*t3.*t5-p.*p_y.*t5.*t6+p_y.*rho_r.*t3.*t5+p_x.*p_z.*t2.*t3.*t7+p_x.*p_z.*t2.*t4.*t6-p_y.*rho_r.*t3.*t4.*t5+p_y.*rho_r.*t5.*t6.*t7)];
out1 = reshape([mt1,mt2],2,3);
end
