function out1 = motoCamVerticalPosition(in1,in2)
%motoCamVerticalPosition
%    OUT1 = motoCamVerticalPosition(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Jun-2025 18:21:19

gamma = in1(:,2);
h_c = in2(:,2);
p = in2(:,3);
rho_r = in2(:,4);
t_r = in2(:,5);
theta = in1(:,3);
t2 = cos(gamma);
t3 = cos(theta);
out1 = t_r+rho_r.*t2-p.*t2.*sin(theta)+h_c.*t2.*t3-rho_r.*t2.*t3;
end
