function out1 = rearContactVelocity(in1,in2,in3)
%rearContactVelocity
%    OUT1 = rearContactVelocity(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Jun-2025 23:40:49

gamma = in1(:,2);
h_c = in3(:,5);
mu = in3(:,1);
omega_x = in2(:,1);
omega_y = in2(:,2);
omega_z = in2(:,3);
p = in3(:,4);
psi = in1(:,1);
rho_r = in3(:,3);
theta = in1(:,3);
v_x = in2(:,4);
v_y = in2(:,5);
v_z = in2(:,6);
t2 = cos(gamma);
t3 = cos(mu);
t4 = cos(psi);
t5 = cos(theta);
t6 = sin(gamma);
t7 = sin(mu);
t8 = sin(psi);
t9 = sin(theta);
t10 = t2.^2;
t11 = 1.0./t2;
et1 = -t8.*t10.*v_x-h_c.*omega_x.*t2.*t4.*t5+h_c.*omega_z.*t3.*t8.*t10-h_c.*omega_y.*t7.*t8.*t10+omega_x.*p.*t2.*t4.*t9+omega_y.*p.*t3.*t8.*t10+omega_z.*p.*t7.*t8.*t10+omega_x.*rho_r.*t2.*t4.*t5-omega_z.*rho_r.*t3.*t8.*t10+omega_y.*rho_r.*t7.*t8.*t10+t2.*t3.*t4.*t9.*v_y+t2.*t4.*t5.*t7.*v_y-t2.*t3.*t4.*t5.*v_z+t2.*t4.*t7.*t9.*v_z+h_c.*omega_x.*t2.*t6.*t8.*t9+omega_x.*p.*t2.*t5.*t6.*t8-omega_y.*rho_r.*t3.*t4.*t5.*t6-omega_z.*rho_r.*t3.*t4.*t6.*t9-omega_z.*rho_r.*t4.*t5.*t6.*t7-omega_x.*rho_r.*t2.*t6.*t8.*t9+omega_y.*rho_r.*t4.*t6.*t7.*t9+omega_z.*rho_r.*t3.*t5.*t8.*t10-omega_y.*rho_r.*t3.*t8.*t9.*t10-omega_y.*rho_r.*t5.*t7.*t8.*t10-omega_z.*rho_r.*t7.*t8.*t9.*t10+t2.*t3.*t5.*t6.*t8.*v_y-t2.*t6.*t7.*t8.*t9.*v_y;
et2 = t2.*t3.*t6.*t8.*t9.*v_z+t2.*t5.*t6.*t7.*t8.*v_z;
et3 = -t4.*t10.*v_x+h_c.*omega_x.*t2.*t5.*t8+h_c.*omega_z.*t3.*t4.*t10-h_c.*omega_y.*t4.*t7.*t10+omega_y.*p.*t3.*t4.*t10-omega_x.*p.*t2.*t8.*t9+omega_z.*p.*t4.*t7.*t10-omega_x.*rho_r.*t2.*t5.*t8-omega_z.*rho_r.*t3.*t4.*t10+omega_y.*rho_r.*t4.*t7.*t10-t2.*t3.*t8.*t9.*v_y-t2.*t5.*t7.*t8.*v_y+t2.*t3.*t5.*t8.*v_z-t2.*t7.*t8.*t9.*v_z+h_c.*omega_x.*t2.*t4.*t6.*t9+omega_x.*p.*t2.*t4.*t5.*t6-omega_x.*rho_r.*t2.*t4.*t6.*t9+omega_y.*rho_r.*t3.*t5.*t6.*t8+omega_z.*rho_r.*t3.*t4.*t5.*t10-omega_y.*rho_r.*t3.*t4.*t9.*t10-omega_y.*rho_r.*t4.*t5.*t7.*t10+omega_z.*rho_r.*t3.*t6.*t8.*t9+omega_z.*rho_r.*t5.*t6.*t7.*t8-omega_y.*rho_r.*t6.*t7.*t8.*t9-omega_z.*rho_r.*t4.*t7.*t9.*t10+t2.*t3.*t4.*t5.*t6.*v_y;
et4 = -t2.*t4.*t6.*t7.*t9.*v_y+t2.*t3.*t4.*t6.*t9.*v_z+t2.*t4.*t5.*t6.*t7.*v_z;
out1 = [-t11.*(et1+et2),t11.*(et3+et4),-t6.*v_x-h_c.*omega_x.*t2.*t9+h_c.*omega_z.*t3.*t6-h_c.*omega_y.*t6.*t7-omega_x.*p.*t2.*t5+omega_y.*p.*t3.*t6+omega_z.*p.*t6.*t7+omega_x.*rho_r.*t2.*t9-omega_z.*rho_r.*t3.*t6+omega_y.*rho_r.*t6.*t7-t2.*t3.*t5.*v_y+t2.*t7.*t9.*v_y-t2.*t3.*t9.*v_z-t2.*t5.*t7.*v_z+omega_z.*rho_r.*t3.*t5.*t6-omega_y.*rho_r.*t3.*t6.*t9-omega_y.*rho_r.*t5.*t6.*t7-omega_z.*rho_r.*t6.*t7.*t9];
end
