function out1 = rearContactVelocityJacobian(in1,in2)
%rearContactVelocityJacobian
%    OUT1 = rearContactVelocityJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Jun-2025 16:52:53

gamma = in1(:,2);
h_c = in2(:,2);
mu = in2(:,1);
p = in2(:,3);
rho_r = in2(:,4);
theta = in1(:,3);
t2 = cos(gamma);
t3 = cos(mu);
t4 = cos(theta);
t5 = sin(gamma);
t6 = sin(mu);
t7 = sin(theta);
t8 = mu+theta;
t9 = h_c.*t3;
t10 = p.*t3;
t11 = rho_r.*t3;
t12 = cos(t8);
t13 = p.*t4;
t14 = h_c.*t6;
t15 = h_c.*t7;
t16 = p.*t6;
t17 = rho_r.*t6;
t18 = sin(t8);
t19 = rho_r.*t7;
t20 = 1.0./t2;
t21 = rho_r.*t12;
t22 = rho_r.*t18;
t24 = -t11;
t26 = -t19;
t27 = t13+t15+t26;
t28 = t9+t16+t21+t24;
out1 = reshape([h_c.*t4-p.*t7-rho_r.*t4,t5.*t27,-t2.*t27,t5.*t20.*t21,t2.*(t10-t14+t17-t22),t5.*(t10-t14+t17-t22),t5.*t20.*t22,t2.*t28,t5.*t28,0.0,-t2,-t5,-t18,t5.*t12,-t2.*t12,t12,t5.*t18,-t2.*t18],[3,6]);
end
