function out1 = verticalSpeedJacobian(in1,in2)
%verticalSpeedJacobian
%    OUT1 = verticalSpeedJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Jun-2025 16:52:53

gamma = in1(:,2);
h_c = in2(:,2);
mu = in2(:,1);
p = in2(:,3);
rho_r = in2(:,4);
theta = in1(:,3);
t2 = cos(gamma);
t3 = cos(mu);
t4 = sin(gamma);
t5 = sin(mu);
t6 = sin(theta);
t7 = mu+theta;
t8 = cos(t7);
t9 = sin(t7);
t10 = 1.0./t2;
t11 = 1.0./t9;
out1 = [-t11.*(h_c.*t6-rho_r.*t6+p.*cos(theta)),-t4.*t10.*t11.*(h_c.*t5-p.*t3-rho_r.*t5+rho_r.*t9),t4.*t10.*t11.*(h_c.*t3+p.*t5-rho_r.*t3+rho_r.*t8),-t4.*t10.*t11,-t8.*t11];
end
