function fvy = verticalSpeedDLT(in1,in2,in3)
%verticalSpeedDLT
%    FVY = verticalSpeedDLT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-May-2025 11:12:10

gamma = in1(:,2);
h_c = in3(:,5);
mu = in3(:,1);
omega_x = in2(:,1);
omega_y = in2(:,2);
omega_z = in2(:,3);
p = in3(:,4);
rho_r = in3(:,3);
theta = in1(:,3);
v_x = in2(:,4);
v_z = in2(:,6);
t2 = cos(gamma);
t3 = cos(mu);
t4 = sin(gamma);
t5 = sin(mu);
t6 = sin(theta);
t7 = mu+theta;
t8 = cos(t7);
t9 = sin(t7);
t10 = 1.0./t2;
t11 = 1.0./t8;
fvy = -t9.*t11.*v_z-omega_x.*t11.*(h_c.*t6-rho_r.*t6+p.*cos(theta))-t4.*t10.*t11.*v_x+omega_z.*t4.*t10.*t11.*(h_c.*t3+p.*t5-rho_r.*t3+rho_r.*t8)-omega_y.*t4.*t10.*t11.*(h_c.*t5-p.*t3-rho_r.*t5+rho_r.*t9);
end
