function H = sharpMotorcycleSteadyStateForcingMatrix(in1)
%sharpMotorcycleSteadyStateForcingMatrix
%    H = sharpMotorcycleSteadyStateForcingMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Dec-2024 09:56:37

%   states = [varphi delta omega_psi v_y omega_varphi omega_delta]
%   inputs = [tau_delta]
%   params = [C_delta C_f1 C_f2 C_r1 C_r2 C_rxz I_fx I_fz I_rx I_rz V Z_f a a_n b e g h i_fy i_ry j k m_f m_r r_f r_r varepsilon]
%
C_delta = in1(1,:);
C_f1 = in1(2,:);
C_f2 = in1(3,:);
C_r1 = in1(4,:);
C_r2 = in1(5,:);
V = in1(11,:);
Z_f = in1(12,:);
a = in1(13,:);
a_n = in1(14,:);
b = in1(15,:);
e = in1(16,:);
g = in1(17,:);
h = in1(18,:);
i_fy = in1(19,:);
i_ry = in1(20,:);
j = in1(21,:);
k = in1(22,:);
m_f = in1(23,:);
m_r = in1(24,:);
r_f = in1(25,:);
r_r = in1(26,:);
varepsilon = in1(27,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = C_f1.*a_n;
t5 = C_f2.*a_n;
t6 = Z_f.*a_n;
t7 = V.^2;
t9 = j.^2;
t10 = varepsilon.*2.0;
t13 = e.*g.*m_f;
t14 = 1.0./V;
t15 = 1.0./r_f;
t16 = 1.0./r_r;
t11 = t2.^2;
t12 = sin(t10);
t17 = -t6;
t18 = 1.0./t2;
t19 = t2.*t4;
t20 = C_r1.*b.*t2;
t21 = t3.*t5;
t22 = a_n.*r_f.*t4;
t23 = t4.*t14;
t24 = V.*i_fy.*t15;
t25 = V.*i_ry.*t16;
t26 = t2.*t24;
mt1 = [0.0,0.0,-t18.*(t5+C_f2.*e+C_r2.*b.*t2-C_f2.*j.*t3-C_f2.*k.*t2),C_f2+C_r2,g.*(h.*m_r+j.*m_f),-t5+t13+t17,0.0,0.0,-t18.*(t19+t21-C_f2.*j+C_f1.*e.*t2+C_f2.*e.*t3-(C_f1.*j.*t12)./2.0+C_f2.*j.*t11-C_f1.*k.*t11-(C_f2.*k.*t12)./2.0),C_f1.*t2+C_f2.*t3,t13+t17,-t19-t21+t3.*t13+t3.*t17,0.0,0.0,-(t14.*(C_f1.*t9-a.*t4.*2.0+a_n.*t4-C_f1.*e.^2-C_f1.*a.*e.*2.0-C_f1.*t9.*t11+C_r1.*b.^2.*t11+C_f1.*k.^2.*t11+k.*m_f.*t7.*t11+C_f1.*j.*k.*t12))./t11];
mt2 = [-t14.*t18.*(-t4-t20+C_f1.*a+m_f.*t2.*t7+m_r.*t2.*t7),-t24-t25-V.*h.*m_r-V.*j.*m_f,-t14.*t15.*t18.*(t22-a.*r_f.*t4+(i_fy.*t7.*t12)./2.0+e.*m_f.*r_f.*t2.*t7),0.0,0.0,t14.*t18.*(t4+t20+C_f1.*e-C_f1.*j.*t3-C_f1.*k.*t2),-t14.*(C_f1+C_r1),0.0,t23,1.0,0.0,t24+t25,0.0,0.0,t26,0.0,1.0,t14.*t15.*t18.*(-t22-e.*r_f.*t4+k.*r_f.*t19+j.*r_f.*t3.*t4+i_fy.*t2.*t3.*t7),t23,-t26,-C_delta-a_n.*t23];
H = reshape([mt1,mt2],6,6);
end
