function M = sharpMotorcycleSteadyStateMassMatrix(in1)
%sharpMotorcycleSteadyStateMassMatrix
%    M = sharpMotorcycleSteadyStateMassMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Dec-2024 09:56:36

%   states = [varphi delta omega_psi v_y omega_varphi omega_delta]
%   inputs = [tau_delta]
%   params = [C_delta C_f1 C_f2 C_r1 C_r2 C_rxz I_fx I_fz I_rx I_rz V Z_f a a_n b e g h i_fy i_ry j k m_f m_r r_f r_r varepsilon]
%
C_rxz = in1(6,:);
I_fx = in1(7,:);
I_fz = in1(8,:);
I_rx = in1(9,:);
I_rz = in1(10,:);
e = in1(16,:);
h = in1(18,:);
j = in1(21,:);
k = in1(22,:);
m_f = in1(23,:);
m_r = in1(24,:);
varepsilon = in1(27,:);
t2 = cos(varepsilon);
t3 = sin(varepsilon);
t4 = e.*m_f;
t5 = h.*m_r;
t6 = j.*m_f;
t7 = k.*m_f;
t8 = varepsilon.*2.0;
t9 = t2.^2;
t10 = sin(t8);
t11 = I_fz.*t2;
t12 = I_fz.*t3;
t13 = j.*t4;
t14 = k.*t4;
t15 = k.*t6;
t18 = t5+t6;
t16 = I_fx.*t9;
t17 = I_fz.*t9;
t19 = t11+t14;
t20 = t12+t13;
t21 = (I_fx.*t10)./2.0;
t22 = (I_fz.*t10)./2.0;
t23 = -t21;
t24 = C_rxz+t15+t22+t23;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,I_fx+I_rz-t16+t17+k.*t7,t7,t24,t19,0.0,0.0,t7,m_f+m_r,t18,t4,0.0,0.0,t24,t18,I_fz+I_rx+t16-t17+h.*t5+j.*t6,t20,0.0,0.0,t19,t4,t20,I_fz+e.*t4],[6,6]);
end
