function solfz = prydeMotoTrimNormalForces(in1)
%prydeMotoTrimNormalForces
%    SOLFZ = prydeMotoTrimNormalForces(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Mar-2026 02:10:07

b = in1(28,:);
b_l = in1(29,:);
b_w = in1(30,:);
f_l = in1(33,:);
g = in1(36,:);
h_u = in1(39,:);
k = in1(44,:);
m_b = in1(48,:);
m_f = in1(49,:);
m_h = in1(50,:);
m_l = in1(51,:);
m_r = in1(52,:);
m_u = in1(53,:);
nu = in1(54,:);
p = in1(57,:);
tau_p = in1(66,:);
t2 = cos(nu);
t3 = sin(nu);
t6 = b.*g.*m_b;
t7 = b.*g.*m_h;
t8 = b_l.*g.*m_l;
t9 = b_w.*g.*m_u;
t10 = g.*k.*m_h;
t11 = 1.0./p;
t12 = -tau_p;
t4 = t2.^2;
t5 = t3.^2;
t13 = g.*h_u.*m_u.*t3;
t14 = t4+t5;
solfz = [t11.*(t6+t7+t8+t9+t10+t12+t13-(f_l.*p)./2.0+g.*m_f.*p);(t14.*(-f_l+g.*m_b.*2.0+g.*m_h.*2.0+g.*m_l.*2.0+g.*m_r.*2.0+g.*m_u.*2.0))./2.0-t11.*t14.*(t6+t7+t8+t9+t10+t12+t13)];
end
