function solfz = prydeMotoTrimNormalForces(in1)
%prydeMotoTrimNormalForces
%    SOLFZ = prydeMotoTrimNormalForces(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Mar-2026 13:06:33

b = in1(21,:);
f_l = in1(24,:);
g = in1(27,:);
k = in1(32,:);
m_b = in1(34,:);
m_f = in1(35,:);
m_h = in1(36,:);
m_r = in1(37,:);
p = in1(40,:);
tau_p = in1(49,:);
t2 = b.*g.*m_b;
t3 = b.*g.*m_h;
t4 = g.*k.*m_h;
t5 = 1.0./p;
t6 = -tau_p;
t7 = f_l./2.0;
t8 = -t7;
t9 = t2+t3+t4+t6;
t10 = t5.*t9;
solfz = [t8+t10+g.*m_f;t8-t10+g.*m_b+g.*m_h+g.*m_r];
end
