classdef Tire < matlab.mixin.SetGet
    properties
        EffectiveRollingRadius;
        SpringRate;
        Mass;
        UndeflectedCrownRadius;
        SpinInertia;
        NominalVerticalForce;
        Pky1;
        Pky2;
        Pky3;
        Pky4;
        Pky5;
        Pky6;
        Pky7;
        Qdz1;
        Qdz2;
        Qdz3;
        Qdz4;
        Qdz8;
        Qdz9;
        Qdz10;
        Qdz11;
    end
end