function f2 = invertedPendulumAndCartBody1DynamicsActiveForcingVector(in1,F_x,in3)
%invertedPendulumAndCartBody1DynamicsActiveForcingVector
%    F2 = invertedPendulumAndCartBody1DynamicsActiveForcingVector(IN1,F_x,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Sep-2025 20:08:33

%   states = [x theta v omega]
%   inputs = [F_x]
%   params = [I_yy b_theta b_x g l m_c m_p]
%
b_x = in3(3,:);
v = in1(3,:);
f2 = [F_x-b_x.*v;0.0];
end
