function M = invertedPendulumAndCartBody1DynamicsMassMatrix(in1,in2)
%invertedPendulumAndCartBody1DynamicsMassMatrix
%    M = invertedPendulumAndCartBody1DynamicsMassMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Sep-2025 20:08:33

%   states = [x theta v omega]
%   inputs = [F_x]
%   params = [I_yy b_theta b_x g l m_c m_p]
%
m_c = in2(6,:);
M = reshape([m_c,0.0,0.0,0.0],[2,2]);
end
