function G = pendulumSSInputMatrix(in1)
%pendulumSSInputMatrix
%    G = pendulumSSInputMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:35

%   states = [theta omega]
%   inputs = [M_y]
%   params = [b g l m t]
%
G = [0.0;-1.0];
end
