function H = pendulumSSForcingMatrix(in1)
%pendulumSSForcingMatrix
%    H = pendulumSSForcingMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:35

%   states = [theta omega]
%   inputs = [M_y]
%   params = [b g l m t]
%
b = in1(1,:);
g = in1(2,:);
l = in1(3,:);
m = in1(4,:);
H = reshape([0.0,g.*l.*m,1.0,b],[2,2]);
end
