function M = pendulumSSMassMatrix(in1)
%pendulumSSMassMatrix
%    M = pendulumSSMassMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:35

%   states = [theta omega]
%   inputs = [M_y]
%   params = [b g l m t]
%
l = in1(3,:);
m = in1(4,:);
M = reshape([1.0,0.0,0.0,-l.^2.*m],[2,2]);
end
