function hp = measurement(in1,in2)
%MEASUREMENT
%    HP = MEASUREMENT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    06-Sep-2024 21:34:17

delta = in1(4,:);
phi = in1(3,:);
psi = in1(1,:);
theta = in1(2,:);
varepsilon = in2(3,:);
t2 = cos(delta);
t3 = cos(phi);
t4 = cos(psi);
t5 = sin(delta);
t6 = cos(theta);
t7 = cos(varepsilon);
t8 = sin(phi);
t9 = sin(psi);
t10 = sin(theta);
t11 = sin(varepsilon);
hp = [-t3.*t5.*t9+t2.*t4.*t6.*t7+t4.*t5.*t8.*t10+t2.*t8.*t9.*t11+t2.*t3.*t4.*t10.*t11;t3.*t4.*t5+t2.*t6.*t7.*t9-t2.*t4.*t8.*t11+t5.*t8.*t9.*t10+t2.*t3.*t9.*t10.*t11;-t2.*t7.*t10+t5.*t6.*t8+t2.*t3.*t6.*t11;-t2.*t3.*t9-t4.*t5.*t6.*t7+t2.*t4.*t8.*t10-t5.*t8.*t9.*t11-t3.*t4.*t5.*t10.*t11;t2.*t3.*t4-t5.*t6.*t7.*t9+t4.*t5.*t8.*t11+t2.*t8.*t9.*t10-t3.*t5.*t9.*t10.*t11;t2.*t6.*t8+t5.*t7.*t10-t3.*t5.*t6.*t11;-t4.*t6.*t11+t7.*t8.*t9+t3.*t4.*t7.*t10;-t4.*t7.*t8-t6.*t9.*t11+t3.*t7.*t9.*t10;t10.*t11+t3.*t6.*t7];
