function hp = motorcycleKinematicsmeasurement(in1,in2)
%motorcycleKinematicsmeasurement
%    HP = motorcycleKinematicsmeasurement(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Sep-2024 15:02:50

delta = in1(4,:);
psi = in1(1,:);
theta = in1(3,:);
varphi = in1(2,:);
varepsilon = in2(4,:);
t2 = cos(delta);
t3 = cos(psi);
t4 = sin(delta);
t5 = cos(theta);
t6 = cos(varphi);
t7 = cos(varepsilon);
t8 = sin(psi);
t9 = sin(theta);
t10 = sin(varphi);
t11 = sin(varepsilon);
mt1 = [-t4.*t6.*t8+t2.*t3.*t5.*t7+t2.*t3.*t9.*t11+t2.*t5.*t8.*t10.*t11-t2.*t7.*t8.*t9.*t10;t3.*t4.*t6+t2.*t5.*t7.*t8+t2.*t8.*t9.*t11-t2.*t3.*t5.*t10.*t11+t2.*t3.*t7.*t9.*t10;t4.*t10+t2.*t5.*t6.*t11-t2.*t6.*t7.*t9;-t2.*t6.*t8-t3.*t4.*t5.*t7-t3.*t4.*t9.*t11-t4.*t5.*t8.*t10.*t11+t4.*t7.*t8.*t9.*t10;t2.*t3.*t6-t4.*t5.*t7.*t8-t4.*t8.*t9.*t11+t3.*t4.*t5.*t10.*t11-t3.*t4.*t7.*t9.*t10;t2.*t10-t4.*t5.*t6.*t11+t4.*t6.*t7.*t9;-t3.*t5.*t11+t3.*t7.*t9+t5.*t7.*t8.*t10+t8.*t9.*t10.*t11];
mt2 = [-t5.*t8.*t11+t7.*t8.*t9-t3.*t5.*t7.*t10-t3.*t9.*t10.*t11;t6.*cos(theta-varepsilon)];
hp = [mt1;mt2];
