function fp = motorcycleKinematicsPrediction(in1,in2,in3)
%PREDICTION
%    FP = PREDICTION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    08-Sep-2024 23:22:21

delta = in1(4,:);
omega_x = in2(1,:);
omega_y = in2(2,:);
omega_z = in2(3,:);
roll = in1(3,:);
theta = in1(2,:);
varepsilon = in3(3,:);
t2 = cos(delta);
t3 = cos(roll);
t4 = sin(delta);
t5 = cos(theta);
t6 = cos(varepsilon);
t7 = sin(roll);
t8 = sin(theta);
t9 = sin(varepsilon);
t10 = t3.^2;
t11 = t5.^2;
t12 = t6.^2;
t14 = t3.*t5.*t6.*t8.*t9;
t13 = t10.*t12;
t16 = -t14;
t15 = t11.*t13;
t17 = -t15;
t18 = t11+t13+t16+t17;
t19 = 1.0./t18;
mt1 = [(t19.*(omega_y.*t2.*t5.*t7.*2.0+omega_x.*t4.*t5.*t7.*2.0+omega_z.*t3.*t5.*t6+omega_x.*t2.*t3.*t5.*t9.*2.0-omega_y.*t3.*t4.*t5.*t9.*2.0-omega_x.*t2.*t6.*t8.*t10+omega_y.*t4.*t6.*t8.*t10-omega_y.*t2.*t3.*t6.*t7.*t8.*t9-omega_x.*t3.*t4.*t6.*t7.*t8.*t9))./2.0;t19.*(omega_y.*t2.*t3.*t11.*-2.0-omega_x.*t3.*t4.*t11.*2.0-omega_y.*t2.*t3.*t12.*2.0-omega_x.*t3.*t4.*t12.*2.0+omega_z.*t6.*t7.*t11+omega_x.*t2.*t7.*t9.*t11.*2.0+omega_y.*t2.*t3.*t11.*t12.*2.0+omega_x.*t3.*t4.*t11.*t12.*2.0-omega_y.*t4.*t7.*t9.*t11.*2.0+omega_y.*t2.*t5.*t6.*t8.*t9+omega_x.*t4.*t5.*t6.*t8.*t9-omega_x.*t2.*t3.*t5.*t6.*t7.*t8+omega_y.*t3.*t4.*t5.*t6.*t7.*t8+omega_y.*t2.*t5.*t6.*t8.*t9.*t10+omega_x.*t4.*t5.*t6.*t8.*t9.*t10).*(-1.0./2.0)];
mt2 = [(t19.*(-omega_z.*t9.*t11+omega_x.*t2.*t6.*t10+omega_x.*t2.*t6.*t11.*2.0-omega_y.*t4.*t6.*t10-omega_y.*t4.*t6.*t11.*2.0+omega_y.*t2.*t5.*t7.*t8+omega_x.*t4.*t5.*t7.*t8+omega_z.*t3.*t5.*t6.*t8-omega_x.*t2.*t6.*t10.*t11+omega_y.*t4.*t6.*t10.*t11+omega_x.*t2.*t3.*t5.*t8.*t9+omega_y.*t2.*t3.*t6.*t7.*t9+omega_x.*t3.*t4.*t6.*t7.*t9-omega_y.*t3.*t4.*t5.*t8.*t9+omega_y.*t2.*t5.*t7.*t8.*t12+omega_x.*t4.*t5.*t7.*t8.*t12-omega_y.*t2.*t3.*t6.*t7.*t9.*t11-omega_x.*t3.*t4.*t6.*t7.*t9.*t11))./2.0];
mt3 = [t19.*(-omega_z.*t11-omega_z.*t13.*2.0+omega_z.*t14.*2.0+omega_z.*t15.*2.0+omega_x.*t2.*t3.*t5.*t8-omega_y.*t2.*t3.*t6.*t7.*2.0-omega_x.*t3.*t4.*t6.*t7.*2.0-omega_y.*t3.*t4.*t5.*t8-omega_x.*t2.*t6.*t9.*t10.*2.0+omega_y.*t4.*t6.*t9.*t10.*2.0-omega_x.*t2.*t3.*t5.*t8.*t12.*2.0+omega_y.*t2.*t3.*t6.*t7.*t11.*2.0+omega_x.*t3.*t4.*t6.*t7.*t11.*2.0+omega_y.*t2.*t5.*t7.*t8.*t9+omega_x.*t4.*t5.*t7.*t8.*t9+omega_y.*t3.*t4.*t5.*t8.*t12.*2.0+omega_x.*t2.*t6.*t9.*t10.*t11.*2.0-omega_y.*t4.*t6.*t9.*t10.*t11.*2.0).*(-1.0./2.0)];
fp = [mt1;mt2;mt3];
