function init(obj, opts)
    arguments
        obj
        opts.Parent (1,1) matlab.graphics.axis.Axes = gca
        opts.Color (1,3) double {mustBeInRange(opts.Color, 0, 1)} = [0,0,0]
        opts.DimensionLines (1,1) string = ""
    end

    obj.XAxis = anim.axis( ...
        "Parent",opts.Parent, ...
        "Color",opts.Color, ...
        "Direction",'x' ...
        );

    obj.YAxis = anim.axis( ...
        "Parent", opts.Parent, ...
        "Color", opts.Color, ...
        "Direction",'y' ...
        );

    obj.ZAxis = anim.axis( ...
        "Parent", opts.Parent, ...
        "Color", opts.Color, ...
        "Direction",'z' ...
        );

    if ismember('x',char(lower(opts.DimensionLines)))
        set(obj.XAxis.DimensionLine,"Visible",'on');
    end

    if ismember('y',char(lower(opts.DimensionLines)))
        set(obj.YAxis.DimensionLine,"Visible",'on');
    end

    if ismember('z',char(lower(opts.DimensionLines)))
        set(obj.ZAxis.DimensionLine,"Visible",'on');
    end
end