function H = prydeMotoLongitudinalSSForcingMatrix(in1)
%prydeMotoLongitudinalSSForcingMatrix
%    H = prydeMotoLongitudinalSSForcingMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Apr-2026 14:48:00

%   states = [v_rx omega_r omega_f kappa_r kappa_f]
%   inputs = [tau_r tau_br tau_bf]
%   params = [C_delta I_bxx I_bxz I_bzz I_hxx I_hzz K_xkf K_xkr K_yaf K_yar K_ygf K_ygr K_zaf K_zar K_zgf K_zgr R_f R_r V a_n b e f_d f_l f_zf f_zr g h i_fy i_ry j k l_x m_b m_f m_h m_r omega_f0 omega_r0 p rho_f rho_r sigma_alpha_f sigma_alpha_r sigma_kappa_f sigma_kappa_r t_f t_r tau_p varepsilon]
%
K_xkf = in1(7,:);
K_xkr = in1(8,:);
R_f = in1(17,:);
R_r = in1(18,:);
V = in1(19,:);
f_d = in1(23,:);
t2 = -V;
H = reshape([0.0,0.0,0.0,-f_d./K_xkr+1.0,1.0,0.0,0.0,0.0,-R_r,0.0,0.0,0.0,0.0,0.0,-R_f,K_xkr,-K_xkr.*R_r,0.0,t2,0.0,K_xkf,0.0,-K_xkf.*R_f,0.0,t2],[5,5]);
end
