function out1 = dynamicBicycle(in1,in2,in3)
%dynamicBicycle
%    OUT1 = dynamicBicycle(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Jul-2024 18:02:30

%    states = [x y psi delta v_x v_y omega_z omega_delta]
%    inputs = [F_x M_delta F_yf F_yr]
%    params = [I_fzz I_rzz l_f l_r m_f m_r]
%
F_x = in2(1,:);
F_yf = in2(3,:);
F_yr = in2(4,:);
I_fzz = in3(1,:);
I_rzz = in3(2,:);
M_delta = in2(2,:);
delta = in1(4,:);
l_f = in3(3,:);
l_r = in3(4,:);
m_f = in3(5,:);
m_r = in3(6,:);
omega_z = in1(7,:);
omega_delta = in1(8,:);
psi = in1(3,:);
v_x = in1(5,:);
v_y = in1(6,:);
t2 = cos(delta);
t3 = cos(psi);
t4 = sin(psi);
t5 = m_f+m_r;
t6 = F_yr.*2.0;
t7 = I_fzz.^2;
t8 = l_f.^2;
t9 = m_f.^2;
t11 = m_f.*omega_z.*v_x;
t12 = m_r.*omega_z.*v_x;
t10 = l_r.*t6;
t13 = l_f.*t11;
t14 = F_yf.*t2.*2.0;
t15 = m_f.*t8;
t16 = -t11;
t17 = -t12;
t19 = t5.*t7;
t20 = F_yf.*l_f.*t2.*-2.0;
t21 = I_fzz.*t8.*t9;
t18 = l_f.*t14;
t22 = I_fzz+I_rzz+t15;
t25 = t10+t13+t20;
t26 = t6+t14+t16+t17;
t23 = I_fzz.*t5.*t22;
t24 = -t23;
t27 = t19+t21+t24;
t28 = 1.0./t27;
t29 = I_fzz.*t5.*t25.*t28;
t30 = I_fzz.*l_f.*m_f.*t26.*t28;
out1 = [t3.*v_x-t4.*v_y;t4.*v_x+t3.*v_y;omega_z;omega_delta;(F_x-F_yf.*sin(delta).*2.0+l_f.*m_f.*omega_z.^2+m_f.*omega_z.*v_y+m_r.*omega_z.*v_y)./t5;t26.*t28.*(t7-I_fzz.*t22)-I_fzz.*M_delta.*l_f.*m_f.*t28-I_fzz.*l_f.*m_f.*t25.*t28;t29+t30+I_fzz.*M_delta.*t5.*t28;-t29-t30+M_delta.*t28.*(t8.*t9-t5.*t22)];
