function vCf = frontContactVelocity(in1,in2)
%frontContactVelocity
%    vCf = frontContactVelocity(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Jul-2024 17:57:09

delta = in1(7,:);
l_f = in2(2,:);
omega_z = in1(6,:);
v_x = in1(4,:);
v_y = in1(5,:);
t2 = cos(delta);
t3 = sin(delta);
vCf = [t2.*v_x+t3.*v_y+l_f.*omega_z.*t3;-t3.*v_x+t2.*v_y+l_f.*omega_z.*t2];
