function vCr = rearContactVelocity(in1,in2)
%rearContactVelocity
%    vCr = rearContactVelocity(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Jul-2024 17:57:09

l_r = in2(3,:);
omega_z = in1(6,:);
v_x = in1(4,:);
v_y = in1(5,:);
vCr = [v_x;v_y-l_r.*omega_z];
