function vCr = rearContactVelocity(in1,in2)
%rearContactVelocity
%    vCr = rearContactVelocity(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Jul-2024 18:02:31

l_r = in2(4,:);
omega_z = in1(7,:);
v_x = in1(5,:);
v_y = in1(6,:);
vCr = [v_x;v_y-l_r.*omega_z];
