function f0 = pendulumBody1DynamicsCentrifugalForcingVector(in1,in2)
%pendulumBody1DynamicsCentrifugalForcingVector
%    F0 = pendulumBody1DynamicsCentrifugalForcingVector(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:33

%   states = [theta omega]
%   inputs = [M_y]
%   params = [b g l m t]
%
f0 = 0.0;
end
