function M = pendulumBody1DynamicsMassMatrix(in1,in2)
%pendulumBody1DynamicsMassMatrix
%    M = pendulumBody1DynamicsMassMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:33

%   states = [theta omega]
%   inputs = [M_y]
%   params = [b g l m t]
%
l = in2(3,:);
m = in2(4,:);
M = -l.^2.*m;
end
