function f2 = pendulumBody1DynamicsActiveForcingVector(in1,M_y,in3)
%pendulumBody1DynamicsActiveForcingVector
%    F2 = pendulumBody1DynamicsActiveForcingVector(IN1,M_y,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:33

%   states = [theta omega]
%   inputs = [M_y]
%   params = [b g l m t]
%
b = in3(1,:);
g = in3(2,:);
l = in3(3,:);
m = in3(4,:);
omega = in1(2,:);
theta = in1(1,:);
f2 = -M_y+b.*omega+g.*l.*m.*sin(theta);
end
