function out1 = pendulum(in1,in2,in3)
%PENDULUM
%    OUT1 = PENDULUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    31-May-2024 15:36:03

%    states = [theta omega]
%    inputs = []
%    params = [b g l m]
%
b = in3(1,:);
g = in3(2,:);
l = in3(3,:);
m = in3(4,:);
omega = in1(2,:);
theta = in1(1,:);
out1 = [omega;-(1.0./l.^2.*(b.*omega-g.*l.*m.*sin(theta)))./m];
