function out1 = pendulum(in1,M_y,in3)
%PENDULUM
%    OUT1 = PENDULUM(IN1,M_y,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Jun-2024 14:37:13

%    states = [theta omega]
%    inputs = [M_y]
%    params = [b g l m]
%
b = in3(1,:);
g = in3(2,:);
l = in3(3,:);
m = in3(4,:);
omega = in1(2,:);
theta = in1(1,:);
out1 = [omega;-(1.0./l.^2.*(-M_y+b.*omega+g.*l.*m.*sin(theta)))./m];
