function G = quadcopterInputMatrix(in1)
%quadcopterInputMatrix
%    G = quadcopterInputMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Nov-2024 21:12:11

%   states = [psi theta phi p_x p_y p_z omega_x omega_y omega_z v_x v_y v_z]
%   inputs = [tau_x tau_y tau_z f_z]
%   params = [I_xx I_yy I_zz g m]
%
G = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[12,4]);
end
