function M = prydeMotorcycleLongitudinalLPVSSMassMatrix(in1)
%prydeMotorcycleLongitudinalLPVSSMassMatrix
%    M = prydeMotorcycleLongitudinalLPVSSMassMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Jul-2025 14:44:47

%   states = [v_rx omega_r omega_f]
%   inputs = [tau_r tau_br tau_bf]
%   params = [A C_d C_delta C_l C_p I_bxx I_bxz I_bzz I_hxx I_hzz K_ycf K_ycr K_yvf K_yvr V a a_n b e f f_zf0 f_zr0 g h i_fy i_ry m_b m_f m_h m_r p_Kxf1 p_Kxf2 p_Kyf1 p_Kxf3 p_Kyf2 p_Kyf3 p_Kyf6 p_Kyf7 p_Kxr1 p_Kxr2 p_Kyr1 p_Kxr3 p_Kyr2 p_Kyr3 p_Kyr6 p_Kyr7 q_dzf1 q_dzf2 q_dzf8 q_dzf9 q_dzr1 q_dzr2 q_dzr8 q_dzr9 rho rho_f rho_r t_f t_r varepsilon]
%
i_fy = in1(25,:);
i_ry = in1(26,:);
m_b = in1(27,:);
m_f = in1(28,:);
m_h = in1(29,:);
m_r = in1(30,:);
M = reshape([-m_b-m_f-m_h-m_r,0.0,0.0,0.0,-i_ry,0.0,0.0,0.0,-i_fy],[3,3]);
end
