function [A,B,C,D,E,dx0,x0,u0,y0,Delays] = prydeMotorcycleLongitudinalDataFcn(~,p)
   %    states = [v_rx omega_r omega_f]
   %    inputs = [tau_r tau_delta]
   %    params = [C_delta I_bxx I_bxz I_bzz I_hxx I_hzz K_xkf K_xkr K_yaf K_ygf K_yar K_ygr K_zaf K_zgf K_zar K_zgr V a a_n b e f g h i_fy i_ry m_b m_h rho_f rho_r t_f t_r varepsilon]
   Sx = prydeMotorcycleLongitudinalStateSelectorMatrix();
   P = prydeMotorcycleLongitudinalPermutationMatrix();
   M = prydeMotorcycleLongitudinalMassMatrix(p);
   H = prydeMotorcycleLongitudinalForcingMatrix(p);
   G = prydeMotorcycleLongitudinalInputMatrix(p);
   Su = prydeMotorcycleLongitudinalInputSelectorMatrix();
   A = Sx*P*(M\H)*Sx.';
   B = Sx*P*(M\G)*Su.';
   C = eye(size(A));
   D = zeros(size(B));
   E = [];
   dx0 = [];
   x0 = zeros(size(A,1),1);
   u0 = zeros(size(B,2),1);
   y0 = zeros(size(A,1),1);
   Delays = [];
