function Su = prydeMotorcycleLongitudinalInputSelectorMatrix
%prydeMotorcycleLongitudinalInputSelectorMatrix
%    Su = prydeMotorcycleLongitudinalInputSelectorMatrix

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    31-Mar-2025 05:22:31

%   states = [v_rx omega_r omega_f]
%   inputs = [tau_r tau_delta]
%   params = [C_delta I_bxx I_bxz I_bzz I_hxx I_hzz K_xkf K_xkr K_yaf K_ygf K_yar K_ygr K_zaf K_zgf K_zar K_zgr V a a_n b e f g h i_fy i_ry m_b m_h rho_f rho_r t_f t_r varepsilon]
%
Su = [1.0,0.0];
end
