function b = body()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.bikebody( ...
        "Parent",gca, ...
        "FileName",dir + "body.stl", ...
        "CoordinateOffset",[0,0,300E-03], ...
        "Color",m.yellow, ...
        "Parameters",anim.bigsports.params ...
        );
end