function b = driver()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.driver( ...
        "Parent",gca, ...
        "FileName",dir + "driver.stl", ...
        "CoordinateOffset",[-85E-03,0,-85E-03], ...
        "Color",0.25*ones(1,3), ...
        "Parameters",anim.bigsports.params ...
        );
end