function b = fork()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.fork( ...
        "Parent",gca, ...
        "FileName",dir + "fork.stl", ...
        "Color",m.green, ...
        "Parameters",anim.bigsports.params ...
        );
end