function b = forktop()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.forktop( ...
        "Parent",gca, ...
        "FileName",dir + "fork_top.stl", ...
        "Color",m.purple, ...
        "Parameters",anim.bigsports.params ...
        );
end