function rt = fronttire()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    rt = anim.fronttire( ...
        "Parent",gca, ...
        "FileName",dir + "front_tire.stl", ...
        "CoordinateOffset",[0,0,0], ...
        "Color",m.cyan, ...
        "Parameters",anim.bigsports.params ...
        );
end