function b = frontfender()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.frontfender( ...
        "Parent",gca, ...
        "FileName",dir + "front_fender.stl", ...
        "AngleOffset",1.5, ...
        "CoordinateOffset",[0,0,-45E-03], ...
        "Color",m.green, ...
        "Parameters",anim.bigsports.params ...
        );
end