function b = handlebars()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.handlebars( ...
        "Parent",gca, ...
        "FileName",dir + "handlebars_no_arms.stl", ...
        "CoordinateOffset",[30E-03,0,50E-03], ...
        "Color",m.purple, ...
        "Parameters",anim.bigsports.params ...
        );
end