function b = leftleg()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.leftleg( ...
        "Parent",gca, ...
        "FileName",dir + "driver_leg_left.stl", ...
        "AngleOffset",[3,6,0], ...
        "CoordinateOffset",[-20E-03,0,0], ...
        "Color",0.25*ones(1,3), ...
        "Parameters",anim.bigsports.params ...
        );
end