function rt = reartire()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    rt = anim.reartire( ...
        "Parent",gca, ...
        "FileName",dir + "rear_tire.stl", ...
        "CoordinateOffset",[0,0,0], ...
        "Color",m.blue, ...
        "Scale",0.95*ones(1,3), ...
        "Parameters",anim.bigsports.params ...
        );
end