function b = rightarm()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    b = anim.rightarm( ...
        "Parent",gca, ...
        "FileName",dir + "right_arm.stl", ...
        "CoordinateOffset",[-50E-03,0,10E-03], ...
        "Scale",[1.05,1,1], ...
        "Color",0.25*ones(1,3), ...
        "Parameters",anim.bigsports.params ...
        );
end