function sa = swingarm()
    dir = "C:\Users\marti\madsym\examples\prydemotorcycle\visualization\BigSports\STL\";
    m = matlabColors;

    sa = anim.swingarm( ...
        "Parent",gca, ...
        "FileName",dir + "swing_arm.stl", ...
        "CoordinateOffset",[1300E-03,0,-5E-03], ...
        "Color",m.orange, ...
        "Parameters",anim.bigsports.params ...
        );
end