function F = constraintJacobianFcn(delta,in2,in3)
%constraintJacobianFcn
%    F = constraintJacobianFcn(DELTA,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    13-Aug-2025 23:05:59

a_n = in3(:,2);
rho_f = in3(:,4);
t_f = in3(:,6);
varphi = in2(:,1);
vartheta = in2(:,2);
varepsilon = in3(:,8);
t2 = cos(delta);
t3 = sin(delta);
t4 = cos(varphi);
t5 = cos(vartheta);
t6 = cos(varepsilon);
t7 = sin(varphi);
t8 = sin(vartheta);
t9 = sin(varepsilon);
t10 = t2.^2;
t11 = t3.^2;
t12 = t4.^2;
t13 = t5.^2;
t14 = t6.^2;
t15 = t2.*t3.*2.0;
t40 = t2.*t3.*t4.*t6.*t7.*t8.*-2.0;
t16 = -t10;
t17 = t10.*t12;
t18 = t12.*t13;
t19 = t12.*t14;
t20 = t12.*t15;
t21 = t2.*t3.*t12.*-2.0;
t27 = t4.*t5.*t7.*t9.*t10.*2.0;
t28 = t4.*t6.*t7.*t8.*t10.*2.0;
t29 = t4.*t5.*t7.*t9.*t11.*2.0;
t30 = t4.*t6.*t7.*t8.*t11.*2.0;
t31 = t5.*t6.*t8.*t9.*t12.*2.0;
t34 = t4.*t5.*t7.*t9.*t15;
t44 = t2.*t3.*t5.*t6.*t8.*t9.*t12.*4.0;
t22 = -t18;
t23 = -t19;
t24 = t13.*t17;
t25 = t14.*t17;
t26 = t14.*t18.*2.0;
t32 = t15.*t18;
t33 = t15.*t19;
t36 = -t28;
t37 = -t29;
t38 = t2.*t3.*t18.*-2.0;
t39 = t2.*t3.*t19.*-2.0;
t42 = t5.*t6.*t8.*t9.*t17.*2.0;
t43 = t2.*t3.*t14.*t18.*4.0;
t41 = t14.*t24.*2.0;
t46 = -t42;
t47 = t15+t21+t27+t30+t36+t37+t38+t39+t43+t44;
t45 = -t41;
t48 = t16+t17+t22+t23+t24+t25+t26+t31+t34+t40+t45+t46+1.0;
t49 = 1.0./sqrt(t48);
t50 = t49.^3;
et1 = -a_n.*t2.*t7+rho_f.*t20.*t49+rho_f.*t28.*t49+rho_f.*t29.*t49+rho_f.*t32.*t49+rho_f.*t33.*t49+(rho_f.*t47.*t50)./2.0-rho_f.*t3.*t4.*t5+rho_f.*t2.*t7.*t9-rho_f.*t2.*t3.*t49.*2.0-(rho_f.*t10.*t47.*t50)./2.0+(rho_f.*t17.*t47.*t50)./2.0-(rho_f.*t18.*t47.*t50)./2.0-(rho_f.*t19.*t47.*t50)./2.0+(rho_f.*t24.*t47.*t50)./2.0+(rho_f.*t25.*t47.*t50)./2.0-t3.*t4.*t5.*t_f+t2.*t7.*t9.*t_f+a_n.*t3.*t4.*t5.*t9-a_n.*t3.*t4.*t6.*t8+rho_f.*t3.*t4.*t5.*t14+rho_f.*t14.*t18.*t47.*t50+t3.*t4.*t5.*t14.*t_f+rho_f.*t3.*t4.*t6.*t8.*t9-rho_f.*t2.*t3.*t14.*t18.*t49.*4.0+rho_f.*t14.*t16.*t18.*t47.*t50+t3.*t4.*t6.*t8.*t9.*t_f-rho_f.*t4.*t5.*t7.*t9.*t10.*t49.*2.0-rho_f.*t4.*t6.*t7.*t8.*t11.*t49.*2.0;
et2 = rho_f.*t5.*t6.*t8.*t9.*t12.*t47.*t50-rho_f.*t2.*t3.*t5.*t6.*t8.*t9.*t12.*t49.*4.0+rho_f.*t2.*t3.*t4.*t5.*t7.*t9.*t47.*t50-rho_f.*t2.*t3.*t4.*t6.*t7.*t8.*t47.*t50+rho_f.*t5.*t6.*t8.*t9.*t12.*t16.*t47.*t50;
F = et1+et2;
end
