function f = constraintFcn(delta,in2,in3)
%constraintFcn
%    F = constraintFcn(DELTA,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    13-Aug-2025 23:05:57

a = in3(:,1);
a_n = in3(:,2);
b = in3(:,3);
rho_f = in3(:,4);
rho_r = in3(:,5);
t_f = in3(:,6);
t_r = in3(:,7);
varphi = in2(:,1);
vartheta = in2(:,2);
varepsilon = in3(:,8);
t2 = cos(delta);
t3 = sin(delta);
t4 = cos(varphi);
t5 = cos(vartheta);
t6 = cos(varepsilon);
t7 = sin(varphi);
t8 = sin(vartheta);
t9 = sin(varepsilon);
t10 = t2.^2;
t11 = t4.^2;
t12 = t5.^2;
t13 = t6.^2;
t14 = 1.0./t6;
t25 = t2.*t3.*t4.*t5.*t7.*t9.*2.0;
t26 = t2.*t3.*t4.*t6.*t7.*t8.*2.0;
t15 = -t10;
t16 = t10.*t11;
t17 = t11.*t12;
t18 = t11.*t13;
t24 = t5.*t6.*t8.*t9.*t11.*2.0;
t27 = -t26;
t19 = -t17;
t20 = -t18;
t21 = t12.*t16;
t22 = t13.*t16;
t23 = t13.*t17.*2.0;
t29 = t5.*t6.*t8.*t9.*t16.*2.0;
t28 = t13.*t21.*2.0;
t31 = -t29;
t30 = -t28;
t32 = t15+t16+t19+t20+t21+t22+t23+t24+t25+t27+t30+t31+1.0;
t33 = 1.0./sqrt(t32);
et1 = -t_f+t_r+rho_r.*t4-rho_f.*t33-a_n.*t3.*t7-b.*t4.*t8-rho_r.*t4.*t5+rho_f.*t10.*t33+rho_f.*t17.*t33+rho_f.*t18.*t33+rho_f.*t26.*t33+rho_f.*t28.*t33+rho_f.*t29.*t33-t4.*t5.*t_r-a.*t4.*t8.*t14+a_n.*t4.*t5.*t9-a_n.*t4.*t6.*t8+a_n.*t4.*t8.*t14+rho_f.*t2.*t4.*t5+rho_f.*t3.*t7.*t9+rho_f.*t4.*t5.*t13+rho_f.*t11.*t15.*t33-rho_f.*t13.*t17.*t33.*2.0+rho_f.*t15.*t17.*t33+rho_f.*t15.*t18.*t33+t2.*t4.*t5.*t_f+t3.*t7.*t9.*t_f+t4.*t5.*t13.*t_f-a_n.*t2.*t4.*t5.*t9+a_n.*t2.*t4.*t6.*t8-rho_f.*t2.*t4.*t5.*t13+rho_f.*t4.*t6.*t8.*t9-t2.*t4.*t5.*t13.*t_f+t4.*t6.*t8.*t9.*t_f-rho_f.*t2.*t4.*t6.*t8.*t9-t2.*t4.*t6.*t8.*t9.*t_f;
et2 = rho_f.*t5.*t6.*t8.*t9.*t11.*t33.*-2.0-rho_f.*t2.*t3.*t4.*t5.*t7.*t9.*t33.*2.0;
f = et1+et2;
end
