function M = prydeMotorcycleLongitudinalSSMassMatrix(in1)
%prydeMotorcycleLongitudinalSSMassMatrix
%    M = prydeMotorcycleLongitudinalSSMassMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    07-Apr-2025 02:26:43

%   states = [v_rx omega_r omega_f]
%   inputs = [tau_r tau_br tau_bf]
%   params = [A C_d C_delta C_l C_p I_bxx I_bxz I_bzz I_hxx I_hzz K_xkf K_xkr K_yaf K_ycf K_ygf K_yar K_ycr K_ygr K_yvf K_yvr K_zaf K_zgf K_zar K_zgr V a a_n b e f g h i_fy i_ry m_b m_f m_h m_r rho rho_f rho_r t_f t_r varepsilon]
%
i_fy = in1(33,:);
i_ry = in1(34,:);
m_b = in1(35,:);
m_f = in1(36,:);
m_h = in1(37,:);
m_r = in1(38,:);
M = reshape([-m_b-m_f-m_h-m_r,0.0,0.0,0.0,-i_ry,0.0,0.0,0.0,-i_fy],[3,3]);
end
