function M = prydeMotorcycleConstraintMassMatrix(in1,in2)
%prydeMotorcycleConstraintMassMatrix
%    M = prydeMotorcycleConstraintMassMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Jul-2025 14:28:49

%   states = [psi p_x p_y varphi theta_r delta theta_f theta psi_f p_fx p_fy varphi_f]
%   inputs = [omega_bz v_rx v_ry omega_bx omega_r omega_delta omega_f omega_by omega_fz v_fx v_fy omega_fx]
%   params = [A C_d C_delta C_l C_p I_bxx I_bxz I_byy I_bzz I_hxx I_hzz K_ycf K_ycr K_yvf K_yvr a a_n b e f f_zf0 f_zr0 g h i_fy i_ry m_b m_f m_h m_r p_Kxf1 p_Kxf2 p_Kxf3 p_Kxr1 p_Kxr2 p_Kxr3 p_Kyf1 p_Kyf2 p_Kyf3 p_Kyf6 p_Kyf7 p_Kyr1 p_Kyr2 p_Kyr3 p_Kyr6 p_Kyr7 q_dzf1 q_dzf2 q_dzf8 q_dzf9 q_dzr1 q_dzr2 q_dzr8 q_dzr9 rho rho_f rho_r t_f t_r varepsilon]
%
a = in2(16,:);
a_n = in2(17,:);
b = in2(18,:);
delta = in1(6,:);
psi_f = in1(9,:);
psi = in1(1,:);
rho_f = in2(56,:);
rho_r = in2(57,:);
t_f = in2(58,:);
t_r = in2(59,:);
theta = in1(8,:);
varphi = in1(4,:);
varphi_f = in1(12,:);
varepsilon = in2(60,:);
t2 = cos(delta);
t3 = cos(psi_f);
t4 = cos(psi);
t5 = sin(delta);
t6 = cos(theta);
t7 = cos(varphi);
t8 = cos(varphi_f);
t9 = cos(varepsilon);
t10 = sin(psi_f);
t11 = sin(psi);
t12 = sin(theta);
t13 = sin(varphi);
t14 = sin(varphi_f);
t15 = sin(varepsilon);
t23 = -a_n;
t16 = t7.^2;
t17 = t8.^2;
t18 = t9.^2;
t19 = t9.^3;
t20 = t15.^2;
t21 = rho_f.*t15;
t22 = t15.*t_f;
t24 = 1.0./t7;
t25 = 1.0./t8;
t26 = 1.0./t9;
t27 = rho_r.*t4.*t6;
t28 = rho_r.*t6.*t11;
t29 = t17-1.0;
t30 = t21+t22+t23;
et1 = t27+b.*t4.*t12+t4.*t6.*t_r+a.*t4.*t9.*t12+b.*t6.*t11.*t13-rho_f.*t4.*t6.*t18-rho_r.*t11.*t12.*t13-t4.*t9.*t12.*t21-t4.*t9.*t12.*t22+t4.*t6.*t15.*t23-t4.*t6.*t18.*t_f-t11.*t12.*t13.*t_r+a.*t6.*t9.*t11.*t13+a.*t4.*t12.*t20.*t26+a_n.*t2.*t4.*t6.*t15+a_n.*t11.*t12.*t13.*t15-rho_f.*t2.*t4.*t6.*t20+rho_f.*t11.*t12.*t13.*t18+t2.*t4.*t9.*t12.*t21+t2.*t4.*t9.*t12.*t22+t2.*t4.*t9.*t12.*t23-t6.*t9.*t11.*t13.*t21-t6.*t9.*t11.*t13.*t22+t4.*t12.*t20.*t23.*t26-t2.*t4.*t6.*t20.*t_f+t11.*t12.*t13.*t18.*t_f+a.*t6.*t11.*t13.*t20.*t26+rho_f.*t2.*t11.*t12.*t13.*t20+t2.*t6.*t9.*t11.*t13.*t21+t2.*t6.*t9.*t11.*t13.*t22+t2.*t6.*t9.*t11.*t13.*t23+t2.*t11.*t12.*t13.*t15.*t23;
et2 = t6.*t11.*t13.*t20.*t23.*t26+t2.*t11.*t12.*t13.*t20.*t_f;
et3 = t28+b.*t11.*t12+t6.*t11.*t_r+a.*t9.*t11.*t12-b.*t4.*t6.*t13-rho_f.*t6.*t11.*t18+rho_r.*t4.*t12.*t13-t9.*t11.*t12.*t21-t9.*t11.*t12.*t22+t6.*t11.*t15.*t23-t6.*t11.*t18.*t_f+t4.*t12.*t13.*t_r-a.*t4.*t6.*t9.*t13+a.*t11.*t12.*t20.*t26+a_n.*t2.*t6.*t11.*t15-rho_f.*t2.*t6.*t11.*t20-rho_f.*t4.*t12.*t13.*t18+t4.*t6.*t9.*t13.*t21+t4.*t6.*t9.*t13.*t22+t2.*t9.*t11.*t12.*t21+t2.*t9.*t11.*t12.*t22+t2.*t9.*t11.*t12.*t23+t4.*t12.*t13.*t15.*t23+t11.*t12.*t20.*t23.*t26-t2.*t6.*t11.*t20.*t_f-t4.*t12.*t13.*t18.*t_f-a.*t4.*t6.*t13.*t20.*t26+a_n.*t2.*t4.*t6.*t9.*t13+a_n.*t2.*t4.*t12.*t13.*t15+a_n.*t4.*t6.*t13.*t20.*t26-rho_f.*t2.*t4.*t12.*t13.*t20;
et4 = -t2.*t4.*t6.*t9.*t13.*t21-t2.*t4.*t6.*t9.*t13.*t22-t2.*t4.*t12.*t13.*t20.*t_f;
mt1 = [t2.*t4.*t6-t5.*t7.*t9.*t11-t2.*t11.*t12.*t13,-t2.*t7.*t12+t5.*t9.*t13,t24.*t26.*(a.*t11.*t16+t11.*t16.*t23+a_n.*t11.*t16.*t18+b.*t9.*t11.*t16+rho_r.*t9.*t11.*t12-t11.*t16.*t18.*t21-t11.*t16.*t18.*t22-rho_r.*t9.*t11.*t12.*t16+t2.*t11.*t16.*t18.*t21+t2.*t11.*t16.*t18.*t22+t2.*t11.*t16.*t18.*t23+t4.*t5.*t6.*t7.*t9.*t21+t4.*t5.*t6.*t7.*t9.*t22+t4.*t5.*t6.*t7.*t9.*t23+a_n.*t5.*t7.*t9.*t11.*t12.*t13-t5.*t7.*t9.*t11.*t12.*t13.*t21-t5.*t7.*t9.*t11.*t12.*t13.*t22)];
mt2 = [t24.*t26.*(-a.*t4.*t16+a_n.*t4.*t16-b.*t4.*t9.*t16-rho_r.*t4.*t9.*t12+t4.*t16.*t18.*t21+t4.*t16.*t18.*t22+t4.*t16.*t18.*t23+a_n.*t2.*t4.*t16.*t18+rho_r.*t4.*t9.*t12.*t16-t2.*t4.*t16.*t18.*t21-t2.*t4.*t16.*t18.*t22+t5.*t6.*t7.*t9.*t11.*t21+t5.*t6.*t7.*t9.*t11.*t22+t5.*t6.*t7.*t9.*t11.*t23+t4.*t5.*t7.*t9.*t12.*t13.*t21+t4.*t5.*t7.*t9.*t12.*t13.*t22+t4.*t5.*t7.*t9.*t12.*t13.*t23),-t26.*(a.*t13+t13.*t23+a_n.*t13.*t18+b.*t9.*t13-t13.*t18.*t21-t13.*t18.*t22-rho_r.*t9.*t12.*t13+t2.*t13.*t18.*t21+t2.*t13.*t18.*t22+t2.*t13.*t18.*t23+t5.*t7.*t9.*t12.*t21+t5.*t7.*t9.*t12.*t22+t5.*t7.*t9.*t12.*t23),0.0,0.0,-t4,-t11,0.0,0.0,0.0];
mt3 = [t11.*t24,-t4.*t24,0.0,-t2.*t4.*t12-t2.*t6.*t11.*t13+t5.*t7.*t11.*t15,-t2.*t6.*t7-t5.*t13.*t15,-t24.*(-t28+t16.*t28-rho_r.*t11.*t16-t11.*t16.*t_r+a_n.*t11.*t15.*t16+rho_f.*t2.*t11.*t16+rho_f.*t11.*t16.*t18+t2.*t11.*t16.*t_f+t11.*t16.*t18.*t_f-rho_f.*t2.*t11.*t16.*t18+t4.*t5.*t7.*t12.*t21+t4.*t5.*t7.*t12.*t22+t4.*t5.*t7.*t12.*t23+t2.*t11.*t15.*t16.*t23-t2.*t11.*t16.*t18.*t_f+t5.*t6.*t7.*t11.*t13.*t21+t5.*t6.*t7.*t11.*t13.*t22+t5.*t6.*t7.*t11.*t13.*t23)];
mt4 = [-t24.*(t27-t16.*t27+rho_r.*t4.*t16+t4.*t16.*t_r-rho_f.*t2.*t4.*t16-rho_f.*t4.*t16.*t18+t4.*t15.*t16.*t23-t2.*t4.*t16.*t_f-t4.*t16.*t18.*t_f+a_n.*t2.*t4.*t15.*t16+rho_f.*t2.*t4.*t16.*t18+t5.*t7.*t11.*t12.*t21+t5.*t7.*t11.*t12.*t22+t5.*t7.*t11.*t12.*t23+t2.*t4.*t16.*t18.*t_f+a_n.*t4.*t5.*t6.*t7.*t13-t4.*t5.*t6.*t7.*t13.*t21-t4.*t5.*t6.*t7.*t13.*t22),-rho_r.*t13-t13.*t_r+a_n.*t13.*t15+rho_f.*t2.*t13+rho_f.*t13.*t18+rho_r.*t6.*t13+t2.*t13.*t_f+t13.*t18.*t_f+a_n.*t5.*t6.*t7-rho_f.*t2.*t13.*t18-t5.*t6.*t7.*t21-t5.*t6.*t7.*t22+t2.*t13.*t15.*t23-t2.*t13.*t18.*t_f,0.0,0.0,0.0,0.0,0.0];
mt5 = [-t5.*t7.*t11+t2.*t4.*t6.*t9+t2.*t4.*t12.*t15+t2.*t6.*t11.*t13.*t15-t2.*t9.*t11.*t12.*t13,t5.*t13+t2.*t6.*t7.*t15-t2.*t7.*t9.*t12,t30.*(t2.*t7.*t11+t4.*t5.*t6.*t9+t4.*t5.*t12.*t15+t5.*t6.*t11.*t13.*t15-t5.*t9.*t11.*t12.*t13),t30.*(-t2.*t4.*t7+t5.*t6.*t9.*t11+t5.*t11.*t12.*t15-t4.*t5.*t6.*t13.*t15+t4.*t5.*t9.*t12.*t13),-t30.*(t2.*t13-t5.*t6.*t7.*t15+t5.*t7.*t9.*t12),0.0,0.0,0.0,0.0,0.0,-t5.*(-t4.*t6.*t15+t4.*t9.*t12+t6.*t9.*t11.*t13+t11.*t12.*t13.*t15),-t5.*t7.*cos(theta-varepsilon),et1+et2,et3+et4];
mt6 = [t7.*t26.*(a.*t6.*t18+a.*t6.*t20+b.*t6.*t9+rho_f.*t12.*t19-rho_r.*t9.*t12-t6.*t18.*t21-t6.*t18.*t22+t6.*t20.*t23+t12.*t19.*t_f-t9.*t12.*t_r+a_n.*t9.*t12.*t15+t2.*t6.*t18.*t21+t2.*t6.*t18.*t22+t2.*t6.*t18.*t23+rho_f.*t2.*t9.*t12.*t20+t2.*t9.*t12.*t15.*t23+t2.*t9.*t12.*t20.*t_f),-t3,0.0,0.0,0.0,0.0,0.0,0.0,t3,t10,0.0,0.0,0.0,-t10.*t25,t3.*t25,0.0,t10.*t14,t8,rho_f.*t10.*t25.*t29,-rho_f.*t3.*t25.*t29,-rho_f.*t14];
M = reshape([mt1,mt2,mt3,mt4,mt5,mt6],5,12);
end
