function M = invertedPendulumAndCartKinematicMassMatrix
%invertedPendulumAndCartKinematicMassMatrix
%    M = invertedPendulumAndCartKinematicMassMatrix

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    21-Sep-2025 20:08:32

%   states = [x theta]
%   inputs = [v omega]
%   params = [I_yy b_theta b_x g l m_c m_p]
%
M = reshape([1.0,0.0,0.0,1.0],[2,2]);
end
