function J = pendulumKinematicJacobian(theta,in2)
%pendulumKinematicJacobian
%    J = pendulumKinematicJacobian(THETA,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:33

%   states = [theta]
%   inputs = [omega]
%   params = [b g l m t]
%
J = 1.0;
end
