function M = pendulumKinematicMassMatrix
%pendulumKinematicMassMatrix
%    M = pendulumKinematicMassMatrix

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Dec-2025 00:00:33

%   states = [theta]
%   inputs = [omega]
%   params = [b g l m t]
%
M = 1.0;
end
